### ISSUE TITLE
allinone interactive bug 

### ISSUE THREAD

**Issue by jkhourybbn** [batfish/batfish#1045]
```
> allinone -runmode interactive
java.lang.NumberFormatException: For input string: "            ("
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:578)
	at java.lang.Long.parseLong(Long.java:631)
	at org.jline.reader.impl.history.DefaultHistory.lambda$load$0(DefaultHistory.java:92)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.jline.reader.impl.history.DefaultHistory.load(DefaultHistory.java:85)
	at org.jline.reader.impl.history.DefaultHistory.attach(DefaultHistory.java:68)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:475)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:390)
	at org.batfish.client.Client.runInteractive(Client.java:2846)
	at org.batfish.client.Client.run(Client.java:2787)
	at org.batfish.allinone.AllInOne.run(AllInOne.java:114)
	at org.batfish.allinone.Main.main(Main.java:6)
```

**Comment by ratulm** [comment]
@jkhourybbn - are you able to reproduce this consistently or was this accidental typing? i use that command all the time. 

where is the string "            (" coming from?

**Comment by jkhourybbn** [comment]
Consistently fails now, used to work before. Not sure where it is getting "   (" from, instead of blocking for my input. Ill can some more debugging later today..

**Comment by ratulm** [comment]
looking at your stack  trace again, it looks like your jline history file is corrupted. remove ~/.batfishclient_history and try.

**Comment by jkhourybbn** [comment]
yup thanks. works now.
