### ISSUE TITLE
Helpful error message when delta testrig is not set

### ISSUE THREAD

**Issue by ratulm** [batfish/batfish#115]
If a differential question is asked when the delta testrig is not set, we get the following error message. A more direct message pointing out the problem will be more helpful.

org.batfish.common.BatfishException: Batfish job failed
   at org.batfish.main.Driver$1.run(Driver.java:366)
Caused by: java.lang.NullPointerException
   at java.nio.file.Files.provider(Files.java:97)
   at java.nio.file.Files.exists(Files.java:2385)
   at org.batfish.main.Batfish.checkBaseDirExists(Batfish.java:662)
   at org.batfish.main.Batfish.environmentExists(Batfish.java:1211)
   at org.batfish.main.Batfish.initQuestionEnvironment(Batfish.java:1969)
   at org.batfish.main.Batfish.initQuestionEnvironments(Batfish.java:1988)
   at org.batfish.main.Batfish.answer(Batfish.java:425)
   at org.batfish.main.Batfish.run(Batfish.java:3340)
   at org.batfish.main.Driver$1.run(Driver.java:333)

**Comment by arifogel** [comment]
fixed by 5fcd8e6c358c8ab661162d0a0c5332d420502b2d
