### ISSUE TITLE
Reachability crash in SynthesizerInputImpl::computeIpsByHostname

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#1249]
Running a reachability question with the following parameters:

```
ingressNodeRegex="<a node>",
finalNodeRegex="<another node>"
specialize=True
actions=["NEIGHBOR_UNREACHABLE_OR_EXITS_NETWORK"]
```

Gets this stack trace.

```
 "answerElements" : [
    {
      "class" : "org.batfish.common.BatfishException$BatfishStackTrace",
      "answer" : [
        "org.batfish.common.BatfishException: Failed to answer question",
        "   at org.batfish.main.Batfish.answer(Batfish.java:634)",
        "   at org.batfish.main.Batfish.run(Batfish.java:3616)",
        "   at org.batfish.main.Driver$2.run(Driver.java:591)",
        "Caused by: java.lang.NullPointerException",
        "   at org.batfish.z3.SynthesizerInputImpl.lambda$computeIpsByHostname$40(SynthesizerInputImpl.java:604)",
        "   at java.util.HashMap.forEach(HashMap.java:1288)",
        "   at org.batfish.z3.SynthesizerInputImpl.computeIpsByHostname(SynthesizerInputImpl.java:601)",
        "   at org.batfish.z3.SynthesizerInputImpl.<init>(SynthesizerInputImpl.java:282)",
        "   at org.batfish.z3.SynthesizerInputImpl$Builder.build(SynthesizerInputImpl.java:87)",
        "   at org.batfish.main.Batfish.computeSynthesizerInput(Batfish.java:4257)",
        "   at org.batfish.main.Batfish.synthesizeDataPlane(Batfish.java:4221)",
        "   at org.batfish.main.Batfish.singleReachability(Batfish.java:4047)",
        "   at org.batfish.main.Batfish.standard(Batfish.java:4171)",
        "   at org.batfish.question.ReachabilityQuestionPlugin$ReachabilityAnswerer.standard(ReachabilityQuestionPlugin.java:87)",
        "   at org.batfish.question.ReachabilityQuestionPlugin$ReachabilityAnswerer.answer(ReachabilityQuestionPlugin.java:44)",
        "   at org.batfish.question.jsonpath.JsonPathQuestionPlugin$JsonPathAnswerer.answer(JsonPathQuestionPlugin.java:166)",
        "   at org.batfish.question.jsonpath.JsonPathQuestionPlugin$JsonPathAnswerer.answer(JsonPathQuestionPlugin.java:135)",
        "   at org.batfish.main.Batfish.answer(Batfish.java:631)",
        "   ... 2 more",
        ""
      ]
    }
  ],
```

Happy to provide concrete network details in person.

**Comment by anothermattbrown** [comment]
This is related to #1234: for `HeaderSpace._dstIps` and `HeaderSpace._srcIps` we currently we use `null` to mean "unconstrained", and `SynthesizerInputImpl` is not handling that case correctly. Short-term fix is to handle `null`. Longer-term fix is to make those `HeaderSpace` fields `@Nonnull IpSpaceConstraints`.
