### ISSUE TITLE
System does not complain when specifying a non-existing interface in bf_init_environment

### ISSUE THREAD

**Issue by ratulm** [batfish/batfish#156]
And then it crashes when running a query. Ideally, checks should be done during both environment creation and when a non-existing interface in encountered during analysis. 

The following exception occurs when running reduced reachability query after creating an environment with non-existing interface

org.batfish.common.BatfishException: Batfish job failed
   at org.batfish.main.Driver$1.run(Driver.java:388)
Caused by: java.lang.NullPointerException
   at org.batfish.main.Batfish.processInterfaceBlacklist(Batfish.java:3456)
   at org.batfish.main.Batfish.loadConfigurations(Batfish.java:2452)
   at org.batfish.bdp.BdpDataPlanePlugin.computeDataPlane(BdpDataPlanePlugin.java:259)
   at org.batfish.main.Batfish.computeDataPlane(Batfish.java:853)
   at org.batfish.main.Batfish.initQuestionEnvironment(Batfish.java:2170)
   at org.batfish.main.Batfish.initQuestionEnvironments(Batfish.java:2183)
   at org.batfish.main.Batfish.answer(Batfish.java:493)
   at org.batfish.main.Batfish.run(Batfish.java:3858)
   at org.batfish.main.Driver$1.run(Driver.java:356)

**Comment by arifogel** [comment]
This falls under general environment validation. So this will be fixed with #163

**Comment by ratulm** [comment]
@arifogel, this is done or something remains?

**Comment by dhalperi** [comment]
I believe this is done. Will verify and follow up with a close.

**Comment by dhalperi** [comment]
Confirm that clients enable environment validation.
