### ISSUE TITLE
Juniper config with zones causes NullPointerException

### ISSUE THREAD

**Issue by plannigan** [batfish/batfish#2025]
When parsing a Juniper config with zones defined, a `null` is placed in `_inboundInterfaceFilters`. The easiest way to demonstrate the issue is to serialize the config to JSON. The `null` is being inserted at the end of `JuniperConfiguration.toZone()`.

Steps to reproduce:
- Create a testrig with a single config that specifies zones. (The sample below is form the batfish test resource `org.batfish.gramar.juniper.testconfigs.firewall-no-policies`) 
```
#
set system host-name firewall-no-policies
#
set security zones security-zone trust interfaces ge-0/0/0.0
set security zones security-zone untrust interfaces ge-0/0/1.0
set interfaces ge-0/0/1 unit 0 family inet address 1.2.4.4/24
set interfaces ge-0/0/0 unit 0 family inet address 1.2.3.4/24
```
- Run batfish allinone
`allinone -runmode inteactive`
- Initialize the testrig and request information about the nodes with summary off
```
init-testrig path/to/testrig/
get nodes summary=false
```

Output:
```
Exception in thread "Thread-160" org.batfish.common.BatfishException: Error in sending answer
	at org.batfish.main.Batfish.outputAnswer(Batfish.java:2614)
	at org.batfish.main.Batfish.outputAnswerWithLog(Batfish.java:2604)
	at org.batfish.main.Driver$2.run(Driver.java:625)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.batfish.datamodel.answers.Answer["answerElements"]->java.util.LinkedList[0]->org.batfish.question.NodesQuestionPlugin$NodesAnswerElement["nodes"]->java.util.TreeMap["firewall-no-policies"]->org.batfish.datamodel.Configuration["zones"]->java.util.TreeMap["trust"]->org.batfish.datamodel.Zone["inboundInterfaceFilters"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFieldsUsing(MapSerializer.java:813)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:637)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFieldsUsing(MapSerializer.java:813)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:637)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:604)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:147)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1396)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1120)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:993)
	at org.batfish.common.util.BatfishObjectMapper.writePrettyString(BatfishObjectMapper.java:105)
	at org.batfish.main.Batfish.outputAnswer(Batfish.java:2609)
	... 2 more
Caused by: java.lang.NullPointerException
	at org.batfish.datamodel.Zone.lambda$getInboundInterfaceFiltersNames$0(Zone.java:147)
	at java.util.TreeMap.forEach(TreeMap.java:1005)
	at org.batfish.datamodel.Zone.getInboundInterfaceFiltersNames(Zone.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:687)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	... 28 more
Status: FAILURE
Question: {
  "class" : "org.batfish.question.NodesQuestionPlugin$NodesQuestion",
  "differential" : false,
  "includeOneTableKeys" : false,
  "nodeRegex" : ".*",
  "summary" : false
}
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.batfish.datamodel.answers.Answer["answerElements"]->java.util.LinkedList[0]->org.batfish.question.NodesQuestionPlugin$NodesAnswerElement["nodes"]->java.util.TreeMap["firewall-no-policies"]->org.batfish.datamodel.Configuration["zones"]->java.util.TreeMap["trust"]->org.batfish.datamodel.Zone["inboundInterfaceFilters"])
org.batfish.common.BatfishException: Error in sending answer
   at org.batfish.main.Batfish.outputAnswer(Batfish.java:2614)
   at org.batfish.main.Batfish.outputAnswerWithLog(Batfish.java:2604)
   at org.batfish.main.Driver$2.run(Driver.java:625)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.batfish.datamodel.answers.Answer["answerElements"]->java.util.LinkedList[0]->org.batfish.question.NodesQuestionPlugin$NodesAnswerElement["nodes"]->java.util.TreeMap["firewall-no-policies"]->org.batfish.datamodel.Configuration["zones"]->java.util.TreeMap["trust"]->org.batfish.datamodel.Zone["inboundInterfaceFilters"])
   at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
   at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
   at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
   at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
   at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
   at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFieldsUsing(MapSerializer.java:813)
   at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:637)
   at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
   at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
   at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
   at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
   at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFieldsUsing(MapSerializer.java:813)
   at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:637)
   at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
   at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
   at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
   at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:604)
   at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:147)
   at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
   at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
   at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
   at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
   at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
   at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1396)
   at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1120)
   at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:993)
   at org.batfish.common.util.BatfishObjectMapper.writePrettyString(BatfishObjectMapper.java:105)
   at org.batfish.main.Batfish.outputAnswer(Batfish.java:2609)
   ... 2 more
Caused by: java.lang.NullPointerException
   at org.batfish.datamodel.Zone.lambda$getInboundInterfaceFiltersNames$0(Zone.java:147)
   at java.util.TreeMap.forEach(TreeMap.java:1005)
   at org.batfish.datamodel.Zone.getInboundInterfaceFiltersNames(Zone.java:145)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:498)
   at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:687)
   at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
   ... 28 more

Summary: 0 (non-assertion) results; 
```
@sfraint

**Comment by dhalperi** [comment]
Thanks for the excellent report! Check out https://github.com/batfish/batfish/pull/2029 -- which fixes the issue on my end.
