### ISSUE TITLE
More NullPointerExceptions

### ISSUE THREAD

**Issue by virtuald** [batfish/batfish#207]
I'm sure I have a configuration error, but I ran into this (partial stack trace below):

```
Caused by: java.lang.NullPointerException
   at org.batfish.bdp.VirtualRouter.initStaticRib(VirtualRouter.java:699)
   at org.batfish.bdp.BdpDataPlanePlugin.lambda$computeFixedPoint$2(BdpDataPlanePlugin.java:324)
   at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
   at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2897)
   at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
   at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
   at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
   at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
   at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
   at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

If I add a check for a null nextHopIp at VirtualRouter:699, then I get by that error, but then there's another one...

```
at org.batfish.bdp.AbstractRib$ByteTrie.getLongestPrefixMatch(AbstractRib.java:37)
   at org.batfish.bdp.AbstractRib.longestPrefixMatch(AbstractRib.java:362)
   at org.batfish.bdp.VirtualRouter.activateStaticRoutes(VirtualRouter.java:188)
   at org.batfish.bdp.BdpDataPlanePlugin.lambda$8(BdpDataPlanePlugin.java:484)
   at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
   at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2897)
   at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
   at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
   at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
   at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
   at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
   at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

And that (VirtualRouter.java:188) also seems like it's using getNextHopIp() without checking to see if it's null or not...

Unfortunately, I can't actually make PRs for this stuff at this time. :(

**Comment by virtuald** [comment]
It looks like the error is that "gateway" must be specified in the host JSON? The following testrig can cause these stack traces:

configs/r1.cfg:

```
interface eth0
  ip address 10.0.4.1/24
!
router ospf 1
  router-id 10.0.4.1
  network 10.0.4.0/24 area 0
!
```

hosts/h1.json:

```
{
  "hostname": "h1",
  "hostInterfaces": {
    "eth0": {
      "name": "eth0",
      "prefix": "10.0.4.12/24"
    }
  }
}
```

With just those two configs, I can cause the stack trace shown above. However, when I add a "gateway" to the hostInterfaces/eth0 of h1.json, then it no longer crashes. Here's the modified h1.json:

```
{
  "hostname": "h1",
  "hostInterfaces": {
    "eth0": {
      "name": "eth0",
      "prefix": "10.0.4.12/24",
      "gateway": "10.0.4.1"
    }
  }
}
```

The gateway key isn't documented in https://github.com/batfish/batfish/wiki/Packaging-testrigs-for-analysis, should it be? Is it required?

**Comment by virtuald** [comment]
And the query I was running was the following:

`get #checkreachability 10.0.4.201 tcp`
