### ISSUE TITLE
list-questions is broken

### ISSUE THREAD

**Issue by virtuald** [batfish/batfish#212]
This is a different kind of failure than #211 . 

```
batfish> list-questions 
exception: org.codehaus.jettison.json.JSONException: JSONObject["questionlist"] is not a JSONArray.
	at org.codehaus.jettison.json.JSONObject.getJSONArray(JSONObject.java:493)
	at org.batfish.client.BfCoordWorkHelper.listQuestions(BfCoordWorkHelper.java:957)
	at org.batfish.client.Client.listQuestions(Client.java:1753)
	at org.batfish.client.Client.processCommand(Client.java:2079)
	at org.batfish.client.Client.processCommand(Client.java:1985)
	at org.batfish.client.Client.runInteractive(Client.java:2319)
	at org.batfish.client.Client.run(Client.java:2272)
	at org.batfish.allinone.AllInOne.run(AllInOne.java:117)
	at org.batfish.allinone.Main.main(Main.java:6)
```

It appears that the returned question list is actually a JSON Object, not an array. And unfortunately, the object is empty, so even if it interpreted it correctly it wouldn't tell me what kinds of questions I can ask. :(

**Comment by dhalperi** [comment]
Hey @virtuald,

These are nice bug reports, but you didn't really provide enough information to reproduce. Can you please say a bit more about how you get there?

Did you just run `allinone` and enter `list-questions`, or were there prior commands, etc?

**Comment by virtuald** [comment]
1. Load a testrig
2. Run list-questions

**Comment by arifogel** [comment]
list-questions show no results because you have not run load-questions. You
need a library of questions to load.

**Comment by dhalperi** [comment]
@arifogel -- either way, the current behavior is a bug – it should not crash as such but should return an empty list. Wei's on it!

**Comment by virtuald** [comment]
I would recommend if an empty list is returned that the client outputs something like "have you ran load-questions first?"

**Comment by dhalperi** [comment]
After #216, this function returns a list instead of crashing. This restores the behavior before recent refactorings.

Further messaging improvements are welcome as pull requests!
