### ISSUE TITLE
object service support

### ISSUE THREAD

**Issue by songtianyi** [batfish/batfish#223]
```
os_service
:
   SERVICE protocol NEWLINE
   //todo: change to os_service_typoe allowing tcp and udp port ranges

;
```
It is not finished yet?

**Comment by songtianyi** [comment]
```
java.lang.NullPointerException
	at org.batfish.grammar.BatfishLexer.mode(BatfishLexer.java:29)
	at org.antlr.v4.runtime.Lexer.pushMode(Lexer.java:188)
	at org.antlr.v4.runtime.atn.LexerPushModeAction.execute(LexerPushModeAction.java:65)
	at org.antlr.v4.runtime.atn.LexerActionExecutor.execute(LexerActionExecutor.java:168)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.accept(LexerATNSimulator.java:369)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(LexerATNSimulator.java:302)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(LexerATNSimulator.java:233)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.match(LexerATNSimulator.java:117)
	at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:141)
	at org.antlr.v4.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:169)
	at org.antlr.v4.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:152)
	at org.antlr.v4.runtime.BufferedTokenStream.nextTokenOnChannel(BufferedTokenStream.java:325)
	at org.antlr.v4.runtime.CommonTokenStream.adjustSeekIndex(CommonTokenStream.java:70)
	at org.antlr.v4.runtime.BufferedTokenStream.consume(BufferedTokenStream.java:137)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:537)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
	at org.batfish.grammar.cisco.CiscoParser.s_object(CiscoParser.java)
	at org.batfish.grammar.cisco.CiscoParser.objects(CiscoParser.java:1903)
	at Demo.main(Demo.java:23)

```

**Comment by songtianyi** [comment]
I'm trying to add rules for object service, but running exception occurred.

**Comment by ratulm** [comment]
Hard to say without knowing what you are doing and what code modifications you made. Can you provide more information?

**Comment by songtianyi** [comment]
here is what i'm trying to add
```g4
os_service
:
   SERVICE NEWLINE
   (
    on_src_dst_detail
   ) NEWLINE
;

on_src_dst_detail
:
    protocol
    (
     src_part
     | dst_part
    )*
;

src_part
:
    SOURCE operator service_port+
;

dst_part
:
    DESTINATION operator service_port+
;

operator
:
    EQ
    | GT
    | LT
    | NEQ
    | RANGE
;

service_port
:
    (SSH | TELNET | WWW)
;
```

**Comment by ratulm** [comment]
still hard to repro. you changed the grammar and then what? it seems to me that you are invoking the grammar code in some non-standard way. what happens if you invoke it in the standard way?

**Comment by ratulm** [comment]
@songtianyi I am closing this issue for now. Please re-open if it is still relevant.
