### ISSUE TITLE
z3-related java exceptions

### ISSUE THREAD

**Issue by networkop** [batfish/batfish#2234]
Hi, I'm trying batfish on my local ubuntu and I'm getting exceptions every time batfish tries to use z3 (it works well for simple config-related queries). I have very little experience with java and maven so I suspect this may be something simple. Here's the list of commands that I do (starting from fresh 16.04)
```bash
apt-get update
apt-get install git lsb-release wget unzip openjdk-8-jdk-headless maven binutils
git clone https://github.com/batfish/batfish.git
cd batfish
tools/install_z3.sh 
source tools/batfish_functions.sh
batfish_build_all
allinone -runmode interactive
```

After that from local java client I do:

```bash
batfish> init-snapshot networks/example tr-base
batfish> get reachability actions=["DROP"], dstIps=["2.128.0.101"], dstProtocols=["dns"]
org.batfish.common.BatfishException: Failed to answer question
   at org.batfish.main.Batfish.answer(Batfish.java:690)
   at org.batfish.main.Batfish.run(Batfish.java:3902)
   at org.batfish.main.Driver.lambda$runBatfish$3(Driver.java:577)
   at java.lang.Thread.run(Thread.java:748)
Caused by: org.batfish.common.BatfishException: Error executing job: no libz3java in java.library.path
   at org.batfish.job.BatfishJobExecutor.executeJobs(BatfishJobExecutor.java:129)
   at org.batfish.job.BatfishJobExecutor.runJobsInExecutor(BatfishJobExecutor.java:71)
   at org.batfish.main.Batfish.computeNodOutput(Batfish.java:1202)
   at org.batfish.main.Batfish.singleReachability(Batfish.java:4342)
   at org.batfish.main.Batfish.standard(Batfish.java:4546)
   at org.batfish.question.ReachabilityQuestionPlugin$ReachabilityAnswerer.standard(ReachabilityQuestionPlugin.java:88)
   at org.batfish.question.ReachabilityQuestionPlugin$ReachabilityAnswerer.answer(ReachabilityQuestionPlugin.java:44)
   at org.batfish.main.Batfish.answer(Batfish.java:687)
   ... 3 more
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: no libz3java in java.library.path
   at java.util.concurrent.FutureTask.report(FutureTask.java:122)
   at java.util.concurrent.FutureTask.get(FutureTask.java:192)
   at org.batfish.job.BatfishJobExecutor.executeJobs(BatfishJobExecutor.java:124)
   ... 10 more
Caused by: java.lang.UnsatisfiedLinkError: no libz3java in java.library.path
   at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
   at java.lang.Runtime.loadLibrary0(Runtime.java:870)
   at java.lang.System.loadLibrary(System.java:1122)
   at com.microsoft.z3.Native.<clinit>(Native.java:14)
   at com.microsoft.z3.Context.<init>(Context.java:41)
   at org.batfish.z3.AbstractNodJob.call(AbstractNodJob.java:97)
   at org.batfish.z3.AbstractNodJob.call(AbstractNodJob.java:26)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   ... 1 more
```

when I try the last command the second time, it throws a different exception:
```
batfish> get reachability actions=["DROP"], dstIps=["2.128.0.101"], dstProtocols=["dns"]
Status: FAILURE
Question: Pretty printing failed. Printing Json
{
  "class" : "org.batfish.question.ReachabilityQuestionPlugin$ReachabilityQuestion",
  "actions" : [
    "DROP"
  ],
  "differential" : false,
  "dstIps" : [
    "2.128.0.101"
  ],
  "dstProtocols" : [
    "dns"
  ],
  "finalNodeRegex" : ".*",
  "includeOneTableKeys" : true,
  "ingressNodeRegex" : ".*",
  "maxChunkSize" : 1,
  "negateHeader" : false,
  "specialize" : true,
  "type" : "standard",
  "useCompression" : false
}
org.batfish.common.BatfishException: Failed to answer question
   at org.batfish.main.Batfish.answer(Batfish.java:690)
   at org.batfish.main.Batfish.run(Batfish.java:3902)
   at org.batfish.main.Driver.lambda$runBatfish$3(Driver.java:577)
   at java.lang.Thread.run(Thread.java:748)
Caused by: org.batfish.common.BatfishException: Error executing job: Could not initialize class com.microsoft.z3.Native
   at org.batfish.job.BatfishJobExecutor.executeJobs(BatfishJobExecutor.java:129)
   at org.batfish.job.BatfishJobExecutor.runJobsInExecutor(BatfishJobExecutor.java:71)
   at org.batfish.main.Batfish.computeNodOutput(Batfish.java:1202)
   at org.batfish.main.Batfish.singleReachability(Batfish.java:4342)
   at org.batfish.main.Batfish.standard(Batfish.java:4546)
   at org.batfish.question.ReachabilityQuestionPlugin$ReachabilityAnswerer.standard(ReachabilityQuestionPlugin.java:88)
   at org.batfish.question.ReachabilityQuestionPlugin$ReachabilityAnswerer.answer(ReachabilityQuestionPlugin.java:44)
   at org.batfish.main.Batfish.answer(Batfish.java:687)
   ... 3 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.z3.Native
   at java.util.concurrent.FutureTask.report(FutureTask.java:122)
   at java.util.concurrent.FutureTask.get(FutureTask.java:192)
   at org.batfish.job.BatfishJobExecutor.executeJobs(BatfishJobExecutor.java:124)
   ... 10 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.z3.Native
   at com.microsoft.z3.Context.<init>(Context.java:41)
   at org.batfish.z3.AbstractNodJob.call(AbstractNodJob.java:97)
   at org.batfish.z3.AbstractNodJob.call(AbstractNodJob.java:26)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   ... 1 more
```

**Comment by dhalperi** [comment]
Hi @networkop  -- did you install the z3 version for your platform?

Step 2 on the getting started instructions: https://github.com/batfish/batfish/wiki/Building-and-running-Batfish-service

If so, please provide more information on your OS and other setup and we'll try to reproduce.

**Comment by networkop** [comment]
yep, I've done that and it seems to have installed successfully. At least I've got z3 libraries copied to their respective directories:
/usr/share/java/com.microsoft.z3.jar
/usr/bin/z3
/usr/lib/libz3.so
/usr/lib/libz3java.so

I'm running everything inside a docker container (on top of fedora 4.17.19-200.fc28.x86_64 ).
So to reproduce you can first fire up the ubuntu container:
```bash
$ docker run -it ubuntu:16.04 bash
```
And then from inside the container I do all the steps from the wiki page you've referenced:
```bash
apt-get update
apt-get install git lsb-release wget unzip openjdk-8-jdk-headless maven binutils
git clone https://github.com/batfish/batfish.git
cd batfish
source tools/batfish_functions.sh
tools/install_z3.sh 
batfish_build_all
allinone -runmode interactive
```

**Comment by dhalperi** [comment]
Hi @networkop  -- I was able to reproduce a similar issue.

If you run `z3` from the command line, do you get any errors?

I found this:

    root@2cbebe35f8fa:/batfish# z3
    z3: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory

which I was able to fix by

    apt-get install libgomp

then Batfish worked.

Give it a try?

**Comment by networkop** [comment]
yep, worked like a charm. Thanks for your help @dhalperi
