### ISSUE TITLE
bug client parsing of answer params

### ISSUE THREAD

**Issue by jkhourybbn** [batfish/batfish#225]
Related to #219,  #224 

if you do 
```
batfish> answer reachability  actions=["drop"], ingressNodeRegex="n(7|8)"
```
it fails during validation
```
org.batfish.common.BatfishException: Variable value "n(7|8)" is not valid JSON
	at org.batfish.client.Client.parseParaValue(Client.java:150)
	at org.batfish.client.Client.validateAndSet(Client.java:177)
	at org.batfish.client.Client.answer(Client.java:625)
	at org.batfish.client.Client.answer(Client.java:690)
	at org.batfish.client.Client.processCommand(Client.java:2015)
	at org.batfish.client.Client.processCommand(Client.java:1992)
	at org.batfish.client.Client.runInteractive(Client.java:2326)
	at org.batfish.client.Client.run(Client.java:2279)
	at org.batfish.client.Main.main(Main.java:29)
```

**Comment by ratulm** [comment]
Fixed (hopefully) by 44850955518d6215de6c88bd095744d93d75822f. Interestingly, what you ran into was an old bug, by which the client wouldn't barf but would ignore the regex. The Java client does not get exercised as much, so all of your reports are useful. 

Closing. Please reopen if you run into more issues.
