### ISSUE TITLE
bug: 0.29.1 broke standalone java client

### ISSUE THREAD

**Issue by jkhourybbn** [batfish/batfish#251]
```
batfish_client -coordinatorhost localhost -runmode interactive
```

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/batfish/datamodel/questions/INodeRegexQuestion
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.batfish.common.plugin.PluginConsumer.loadPluginJar(PluginConsumer.java:163)
	at org.batfish.common.plugin.PluginConsumer.access$000(PluginConsumer.java:36)
	at org.batfish.common.plugin.PluginConsumer$1.visitFile(PluginConsumer.java:217)
	at org.batfish.common.plugin.PluginConsumer$1.visitFile(PluginConsumer.java:212)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.batfish.common.plugin.PluginConsumer.loadPlugins(PluginConsumer.java:212)
	at org.batfish.client.Client.run(Client.java:2228)
	at org.batfish.client.Main.main(Main.java:29)
Caused by: java.lang.ClassNotFoundException: org.batfish.datamodel.questions.INodeRegexQuestion
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by arifogel** [comment]
I cannot reproduce. Did you do a full clean and rebuild?

**Comment by arifogel** [comment]
Also @jkhourybbn how are you building? To make the jars for use on the command line, you must do `mvn install` from the `<batfish-repo>/projects` directory.

**Comment by jkhourybbn** [comment]
doesn't batfish_build_all do that?

**Comment by jkhourybbn** [comment]
I have been doing 
```
batfish_build_all distclean
batfish_build_all
```
to build

**Comment by arifogel** [comment]
Assuming you came from a non-maven (<=0.28.0) version you must start a fresh shell and source `batfish_functions.sh` again. Otherwise those build commands will have old incompatible behavior.
Also, arguments after `batfish_build_all` are no longer supported (I believe they are ignored).

**Comment by jkhourybbn** [comment]
Ok I had to do source in my client window (was only doing it in the server window). thanks!
