### ISSUE TITLE
Every once in a while, coordinator loses a work item(?)

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#2665]
This is a bit indirect, but here's what I see:

Every once in a while, an integration test goes out to lunch. When this happens, here's a stack trace.
[stack.log](https://github.com/batfish/batfish/files/2593844/stack.log)

Relevant snippets include:

```
"coordinatorThread" #11 prio=5 os_prio=31 tid=0x00007f9be48c8800 nid=0xa903 waiting on condition [0x00007000020de000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at org.batfish.coordinator.Main.mainRun(Main.java:417)
        at org.batfish.coordinator.Main.main(Main.java:383)
        at org.batfish.allinone.AllInOne$2.run(AllInOne.java:233)

"main" #1 prio=5 os_prio=31 tid=0x00007f9be6001800 nid=0x1903 waiting on condition [0x0000700000da5000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at org.batfish.client.Client.pollWork(Client.java:2181)
        at org.batfish.client.Client.pollWorkAndGetAnswer(Client.java:2198)
        at org.batfish.client.Client.execute(Client.java:1075)
        at org.batfish.client.Client.initSnapshot(Client.java:1696)
        at org.batfish.client.Client.processCommand(Client.java:2469)
        at org.batfish.client.Client.processCommand(Client.java:2355)
        at org.batfish.client.Client.test(Client.java:3176)
        at org.batfish.client.Client.processCommand(Client.java:2558)
        at org.batfish.client.Client.processCommand(Client.java:2355)
        at org.batfish.client.Client.processCommand(Client.java:2330)
        at org.batfish.client.Client.processCommands(Client.java:2695)
        at org.batfish.client.Client.runBatchFile(Client.java:2827)
        at org.batfish.client.Client.run(Client.java:2772)
        at org.batfish.allinone.AllInOne.run(AllInOne.java:130)
        at org.batfish.allinone.Main.main(Main.java:6)
```

It appears that the coordinator is waiting for new work, and the client is polling old work. How can this happen? Is this a problem with the work item lifecycle that @ratulm implemented?

cc: @corinaminer since she reviewed most of this code and, as I recall, has a very good understanding of it.

**Comment by dhalperi** [comment]
Have not found a repro on this, but did push a PR that may have fixed a bug there... so closing for now and will watch it.
