### ISSUE TITLE
java client deserialization exception

### ISSUE THREAD

**Issue by jkhourybbn** [batfish/batfish#2873]
I am trying to test the new BDD reachability using the Java client but getting an exception with the BDD response deserialization. I don't see the exception if I use the NoD engine. 

```bash
batfish> get reachability ingressNodeRegex=cc-h1
Garbage collection #1: 10007 nodes / 0 free / 0.002s / 0.002s total
Resizing node table from 10007 to 20011
org.batfish.common.BatfishException: Response does not appear to be valid JSON representation of Answer
	at org.batfish.client.Client.pollWorkAndGetAnswer(Client.java:2222)
	at org.batfish.client.Client.execute(Client.java:1075)
	at org.batfish.client.Client.answerFile(Client.java:764)
	at org.batfish.client.Client.answerType(Client.java:816)
	at org.batfish.client.Client.get(Client.java:1216)
	at org.batfish.client.Client.processCommand(Client.java:2423)
	at org.batfish.client.Client.processCommand(Client.java:2355)
	at org.batfish.client.Client.processCommand(Client.java:2330)
	at org.batfish.client.Client.runInteractive(Client.java:2843)
	at org.batfish.client.Client.run(Client.java:2787)
	at org.batfish.allinone.AllInOne.run(AllInOne.java:130)
	at org.batfish.allinone.Main.main(Main.java:6)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot find a (Map) Key deserializer for type [simple type, class org.batfish.datamodel.Flow]
 at [Source: (String)"{
  "answerElements" : [
    {
      "class" : "org.batfish.datamodel.flow.TraceWrapperAsAnswerElement",
      "flowTraces" : {
        "Flow<ingressNode:cc-h1 ingressVrf:default srcIp:0.0.0.0 dstIp:10.10.10.1 ipProtocol:ICMP dscp: 0 ecn:0 fragmentOffset:0 icmpType:8 icmpCode:0 packetLength:0 state:NEW tag:BASE>" : [
          {
            "disposition" : "ACCEPTED",
            "hops" : [
              {
                "node" : {
                  "id" : "node-cc-h1",
                  "name""[truncated 2434 chars]; line: 4, column: 17] (through reference chain: org.batfish.datamodel.answers.Answer["answerElements"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1452)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._handleUnknownKeyDeserializer(DeserializerCache.java:599)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findKeyDeserializer(DeserializerCache.java:168)
	at com.fasterxml.jackson.databind.DeserializationContext.findKeyDeserializer(DeserializationContext.java:500)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.createContextual(MapDeserializer.java:248)
	at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:651)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:484)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:444)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:194)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at org.batfish.client.Client.pollWorkAndGetAnswer(Client.java:2218)
	... 11 more
```

**Comment by dhalperi** [comment]
Does this happen in Pybatfish? The Java client is essentially unsupported.

**Comment by jkhourybbn** [comment]
Sorry I don't use the python client. 

Is the plan to stop supporting the Java client? that would be unfortunate.

**Comment by ratulm** [comment]
The root cause is that the recently added class TraceWrapperAsAnswerElement is not Jackson deserializable as currently written.

**Comment by dhalperi** [comment]
`TraceWrapperAsAnswerElement` was written months ago; in general, the Java client itself is not something we're spending resources supporting.

Happy to review a PR!

**Comment by jkhourybbn** [comment]
@ratulm thanks. I am looking at the answer question and templates: what is the right workflow there? does one have to create a question JSON first, load it, then call answer? 

I noticed that even if you pass questions template dir to batfish, the only way I could see to make the templates available to answer is by explicitly loading the questions using `load-questions` (even though they are part of the template directory and are already loaded by batfish coordinator. Am I missing some detail?

**Comment by jkhourybbn** [comment]
> Hi @jkhourybbn, does the documentation on templates clear it up?
> 
> https://github.com/batfish/batfish/tree/master/questions#batfish-questions-and-templates

Yes this answers it thanks. I sort of backtracked into it :) starting with Ratul's comment. Ill be using the answer templates going forward. I also managed to get a basic python client working so trying that out.  I don't think the python client should be a replacement. If you have a workflow for using the java client like Ratul recommended (templates and answer) and we keep supporting that, that would be great. I also see ur travis is still dependent on it.
