### ISSUE TITLE
Batfish exception in postProcessInterfaceDependecies

### ISSUE THREAD

**Issue by rabeckett** [batfish/batfish#2932]
When running a Pybatfish script on the most recent Batfish master branch, I get an exception, like the one below, that says a loopback address is not a valid vertex. This happens for most networks I try:

```
*** SERIALIZING 13 VENDOR-INDEPENDENT CONFIGURATION STRUCTURES FOR SNAPSHOT 632E2D04-6C93-49C7-8437-413CC68094A5***
Exception in container:640607c1-03e1-4f7c-b53c-79814668b128, testrig:632e2d04-6c93-49c7-8437-413cc68094a5; exception:java.lang.IllegalArgumentException: no such vertex in graph: loopback1
        at org.jgrapht.graph.AbstractGraph.assertVertexExist(AbstractGraph.java:131)
        at org.jgrapht.graph.AbstractBaseGraph.addEdge(AbstractBaseGraph.java:309)
        at org.batfish.main.Batfish.lambda$null$24(Batfish.java:2500)
        at java.lang.Iterable.forEach(Unknown Source)
        at org.batfish.main.Batfish.lambda$null$25(Batfish.java:2498)
        at java.lang.Iterable.forEach(Unknown Source)
        at org.batfish.main.Batfish.lambda$postProcessInterfaceDependencies$26(Batfish.java:2494)
        at java.lang.Iterable.forEach(Unknown Source)
        at org.batfish.main.Batfish.postProcessInterfaceDependencies(Batfish.java:2487)
        at org.batfish.main.Batfish.updateBlacklistedAndInactiveConfigs(Batfish.java:2971)
        at org.batfish.main.Batfish.postProcessSnapshot(Batfish.java:2995)
        at org.batfish.main.Batfish.serializeIndependentConfigs(Batfish.java:3287)
        at org.batfish.main.Batfish.run(Batfish.java:3071)
        at org.batfish.main.Driver.lambda$runBatfish$3(Driver.java:580)
        at java.lang.Thread.run(Unknown Source)
{
  "answerElements" : [
    {
      "class" : "org.batfish.common.BatfishException$BatfishStackTrace",
      "answer" : [
        "org.batfish.common.BatfishException: Batfish job failed\r",
        "   at org.batfish.main.Driver.lambda$runBatfish$3(Driver.java:620)\r",
        "   at java.lang.Thread.run(Unknown Source)\r",
        "Caused by: java.lang.IllegalArgumentException: no such vertex in graph: loopback1\r",
        "   at org.jgrapht.graph.AbstractGraph.assertVertexExist(AbstractGraph.java:131)\r",
        "   at org.jgrapht.graph.AbstractBaseGraph.addEdge(AbstractBaseGraph.java:309)\r",
        "   at org.batfish.main.Batfish.lambda$null$24(Batfish.java:2500)\r",
        "   at java.lang.Iterable.forEach(Unknown Source)\r",
        "   at org.batfish.main.Batfish.lambda$null$25(Batfish.java:2498)\r",
        "   at java.lang.Iterable.forEach(Unknown Source)\r",
        "   at org.batfish.main.Batfish.lambda$postProcessInterfaceDependencies$26(Batfish.java:2494)\r",
        "   at java.lang.Iterable.forEach(Unknown Source)\r",
        "   at org.batfish.main.Batfish.postProcessInterfaceDependencies(Batfish.java:2487)\r",
        "   at org.batfish.main.Batfish.updateBlacklistedAndInactiveConfigs(Batfish.java:2971)\r",
        "   at org.batfish.main.Batfish.postProcessSnapshot(Batfish.java:2995)\r",
        "   at org.batfish.main.Batfish.serializeIndependentConfigs(Batfish.java:3287)\r",
        "   at org.batfish.main.Batfish.run(Batfish.java:3071)\r",
        "   at org.batfish.main.Driver.lambda$runBatfish$3(Driver.java:580)\r",
        "   ... 1 more\r",
        ""
      ]
    }
  ],
  "status" : "FAILURE",
  "summary" : {
    "numFailed" : 0,
    "numPassed" : 0,
    "numResults" : 0
  }
}
```

**Comment by rabeckett** [comment]
Digging a bit, it looks like there may be a capitalization issue. It is trying to add an edge between `loopback1` and `Tunnel1`, but the map returned by `allInterfaces()`, which is used to create vertices, only has an entry for `Loopback1`. The configuration files only use the lowercase `loopback1`.

**Comment by dhalperi** [comment]
Sounds like we're not normalizing the config somewhere. Where is this
`loopback1` used in the config?

**Comment by dhalperi** [comment]
If it's in a blacklist file you provided, you need to keep the interface names in canonical form.

**Comment by rabeckett** [comment]
no blacklist file provided.
running grep for "loopback1" gives the following lines (with addresses changed):
```
ip tftp source-interface loopback1
snmp-server source-interface trap loopback1
snmp-server host 1.2.3.4 source-interface loopback1
ntp source-interface  loopback1
  tunnel source loopback1
interface loopback1
ip source loopback1 icmp-errors
logging source-interface loopback1
```

**Comment by dhalperi** [comment]
Thanks for the report; posted a fix for review.
