### ISSUE TITLE
Error running reduced reachability twice in a row

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#335]
Command log:

```
init-testrig test_rigs/example
get environmentcreation interfaceBlacklist=[{hostname="as2border2",interface="GigabitEthernet0/0"}]
get reachability type=reduced
get reachability type=reduced
```

the first time the get command succeeds, the second time it fails:

```
WMS:getObject tr_040c5622-9146-437d-ac75-3b94d591c877 --> 557cc005-da67-4472-823e-e608f6137813.log
200 OK InboundJaxrsResponse{context=ClientResponse{method=POST, uri=http://localhost:9997/batfishworkmgr/getobject, status=200, reason=OK}}
org.batfish.common.QuestionException: Exception answering question
	at org.batfish.datamodel.answers.Answer.append(Answer.java:42)
	at org.batfish.main.Batfish.run(Batfish.java:3861)
	at org.batfish.main.Driver$1.run(Driver.java:370)
Caused by: org.batfish.common.BatfishException: Failed to answer question
	at org.batfish.main.Batfish.answer(Batfish.java:536)
	... 2 more
Caused by: org.batfish.common.BatfishException: Cannot disable non-existent interface 'GigabitEthernet0/0' on node 'as2border2'

	at org.batfish.main.Batfish.processInterfaceBlacklist(Batfish.java:3378)
	at org.batfish.main.Batfish.loadConfigurations(Batfish.java:2406)
	at org.batfish.main.Batfish.reducedReachability(Batfish.java:3591)
	at org.batfish.question.ReachabilityQuestionPlugin$ReachabilityAnswerer.reducedReachability(ReachabilityQuestionPlugin.java:77)
	at org.batfish.question.ReachabilityQuestionPlugin$ReachabilityAnswerer.answerDiff(ReachabilityQuestionPlugin.java:57)
	at org.batfish.main.Batfish.answer(Batfish.java:531)
	... 2 more
```

**Comment by ratulm** [comment]
Recent cache management changes seem to have fixed this issue.
