### ISSUE TITLE
Some error about run-analysis

### ISSUE THREAD

**Issue by hbbbbb** [batfish/batfish#3551]
I am reading and debugging the batfish code on my macbook with Eclipse(JDK 1.8). I use the interactive mode to study each command in client. When I run command "run-analysis",batfish reported some error:
  batfish> run-analysis hb
exception: org.batfish.common.BatfishException: Cannot queue dataplane dependent work for e48224cd-2679-4319-9e9e-0f346a60946e: Status is DATAPLANING_FAIL but no incomplete dataplaning work exists
	at org.batfish.coordinator.WorkQueueMgr.getBlockerForDataplaneDependentWork(WorkQueueMgr.java:182)
	at org.batfish.coordinator.WorkQueueMgr.queueDependentAnsweringWork(WorkQueueMgr.java:562)
	at org.batfish.coordinator.WorkQueueMgr.queueUnassignedWork(WorkQueueMgr.java:675)
	at org.batfish.coordinator.WorkQueueMgr.processTaskCheckResult(WorkQueueMgr.java:477)
	at org.batfish.coordinator.WorkMgr.checkTask(WorkMgr.java:496)
	at org.batfish.coordinator.WorkMgr.checkTasks(WorkMgr.java:379)
	at org.batfish.coordinator.WorkMgr.access$0(WorkMgr.java:369)
	at org.batfish.coordinator.WorkMgr$AssignWorkTask.run(WorkMgr.java:184)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Failed to get answer file fc4f879b-bc0b-4195-ab9f-e3177eaf7ed7.json. (Was work killed?)

What's wrong, I can't find the problem, so I need your help! Thanks!

**Comment by dhalperi** [comment]
Hi, thanks for the report.

The Java client is not a supported client; please use pybatfish. You can run pybatfish against a local version of batfish by installing it in a local python environment: https://github.com/batfish/batfish/#install-pybatfish

In this case, it looks like you are trying to run a question that requires the data plane to have been produced, but Batfish ran into an error trying to produce the data plane. For more information, use pybatfish [`bf_generate_dataplane()`](https://pybatfish.readthedocs.io/en/latest/api.html#pybatfish.client.commands.bf_generate_dataplane).

**Comment by hbbbbb** [comment]
Thanks for your advice, I will continue studying.Thank you!!!

> Hi, thanks for the report.
> 
> The Java client is not a supported client; please use pybatfish. You can run pybatfish against a local version of batfish by installing it in a local python environment: https://github.com/batfish/batfish/#install-pybatfish
> 
> In this case, it looks like you are trying to run a question that requires the data plane to have been produced, but Batfish ran into an error trying to produce the data plane. For more information, use pybatfish [`bf_generate_dataplane()`](https://pybatfish.readthedocs.io/en/latest/api.html#pybatfish.client.commands.bf_generate_dataplane).
