### ISSUE TITLE
EIGRP Data Plane compute issue

### ISSUE THREAD

**Issue by chiragvyas50** [batfish/batfish#4051]
While analyzing the snapshot with EIGRP configuration getting Data Plane compute  error. config files are also attached.

**Here is the logs from the docker container**
```
Computing Data Plane using iBDP
Exception in container:942afc08-7e58-4699-9eb5-633db122a433, testrig:49d53d53-e922-4db2-a078-aa958332202b; exception:java.lang.ArithmeticException: / by zero
        at org.batfish.datamodel.eigrp.EigrpMetric.classicToNamedBandwidth(EigrpMetric.java:91)
        at org.batfish.datamodel.eigrp.EigrpMetric.accumulate(EigrpMetric.java:119)
        at org.batfish.dataplane.ibdp.VirtualEigrpProcess.propagateInternalRoutesFromNeighbor(VirtualEigrpProcess.java:336)
        at org.batfish.dataplane.ibdp.VirtualEigrpProcess.lambda$propagateInternalRoutes$4(VirtualEigrpProcess.java:299)
        at org.batfish.dataplane.ibdp.VirtualEigrpProcess.propagateInternalRoutes(VirtualEigrpProcess.java:303)
        at org.batfish.dataplane.ibdp.VirtualRouter.lambda$propagateEigrpInternalRoutes$27(VirtualRouter.java:1270)
        at org.batfish.dataplane.ibdp.VirtualRouter.propagateEigrpInternalRoutes(VirtualRouter.java:1271)
        at org.batfish.dataplane.ibdp.IncrementalBdpEngine.lambda$initEigrpInternalRoutes$41(IncrementalBdpEngine.java:795)
```

**pybatfish error message**
```
In [4]: routes_all = bfq.routes().answer().frame()
status: BLOCKED
.... no task information
status: BLOCKED
.... no task information
status: BLOCKED
.... no task information
status: REQUEUEFAILURE
.... Mon Jun 10 15:15:16 2019 PDT Couldn't requeue after unblocking.
Cannot queue dataplane dependent work for 49d53d53-e922-4db2-a078-aa958332202b: Status is DATAPLANING_FAIL but no incomplete dataplaning work exists.
---------------------------------------------------------------------------
BatfishException                          Traceback (most recent call last)
<ipython-input-4-3bc1c9106a9b> in <module>
----> 1 routes_all = bfq.routes().answer().frame()

~/virtual-enviornment/pybatfish-venv/lib/python3.7/site-packages/pybatfish/question/question.py in answer(self, snapshot, reference_snapshot, include_one_table_keys, background, extra_args)
    184                               snapshot=real_snapshot,
    185                               reference_snapshot=reference_snapshot,
--> 186                               extra_args=extra_args)
    187
    188     def dict(self):

~/virtual-enviornment/pybatfish-venv/lib/python3.7/site-packages/pybatfish/client/internal.py in _bf_answer_obj(session, question_str, parameters_str, question_name, background, snapshot, reference_snapshot, extra_args)
     46     work_item = workhelper.get_workitem_answer(session, question_name,
     47                                                snapshot, reference_snapshot)
---> 48     workhelper.execute(work_item, session, background, extra_args)
     49
     50     if background:

~/virtual-enviornment/pybatfish-venv/lib/python3.7/site-packages/pybatfish/client/workhelper.py in execute(work_item, session, background, extra_args)
    136                     work_item.to_json(),
    137                     json.loads(
--> 138                         task_details)))
    139
    140         # Handle fail condition with logs

BatfishException: Work finished with status REQUEUEFAILURE
work_item: {"containerName": "pcpff1b8609-0d6c-4614-a4c1-4f87fe728902", "id": "975097c5-c99e-4b9c-b33a-0e8b200f6c28", "requestParams": {"answer": "", "questionname": "__routes_c2f032ea-5015-454d-bf80-3793940fe305", "testrig": "ss_00cd1542-06cb-4e8a-a8a4-6e888156cb35"}, "testrigName": "ss_00cd1542-06cb-4e8a-a8a4-6e888156cb35"}
task_details: {'batches': [{'completed': 0, 'description': "Couldn't requeue after unblocking.\nCannot queue dataplane dependent work for 49d53d53-e922-4db2-a078-aa958332202b: Status is DATAPLANING_FAIL but no incomplete dataplaning work exists", 'size': 0, 'startDate': '2019-06-10T22:15:16.014+0000'}], 'obtained': '2019-06-10T22:15:16.014+0000', 'status': 'RequeueFailure'}
```
[hqborder1.txt](https://github.com/batfish/batfish/files/3274049/hqborder1.txt)
[hqborder2.txt](https://github.com/batfish/batfish/files/3274050/hqborder2.txt)
[hqdist1.txt](https://github.com/batfish/batfish/files/3274051/hqdist1.txt)
[hqdist2.txt](https://github.com/batfish/batfish/files/3274052/hqdist2.txt)

**Comment by chiragvyas50** [comment]
[EIGRPissue.zip](https://github.com/batfish/batfish/files/3277780/EIGRPissue.zip)
 Uploading snapshot zip
