### ISSUE TITLE
Nullpointer with getNodes

### ISSUE THREAD

**Issue by jkhourybbn** [batfish/batfish#437]
I have two test rigs (base and delta) with only difference being some host iptables rules

After initializing test rig and delta testrig
```
get nodes differential=true
```
results in 
```
Caused by: java.lang.NullPointerException
   at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
   at java.util.regex.Matcher.reset(Matcher.java:309)
   at java.util.regex.Matcher.<init>(Matcher.java:229)
   at java.util.regex.Pattern.matcher(Pattern.java:1093)
   at org.batfish.datamodel.IpAccessListsDiff.getAclLineWithoutSequence(IpAccessListsDiff.java:56)
   at org.batfish.datamodel.IpAccessListsDiff.genDiffInfo(IpAccessListsDiff.java:42)
   at org.batfish.datamodel.IpAccessListsDiff.<init>(IpAccessListsDiff.java:26)
   at org.batfish.datamodel.ConfigurationDiff.<init>(ConfigurationDiff.java:56)
   at org.batfish.question.NodesQuestionPlugin$NodesDiffAnswerElement.generateDiff(NodesQuestionPlugin.java:429)
   at org.batfish.question.NodesQuestionPlugin$NodesDiffAnswerElement.<init>(NodesQuestionPlugin.java:417)
   at org.batfish.question.NodesQuestionPlugin$NodesAnswerer.answerDiff(NodesQuestionPlugin.java:381)
   at org.batfish.main.Batfish.answer(Batfish.java:535)
   ... 2 more
```

**Comment by dhalperi** [comment]
@kidsbear can you take a look at this one?

**Comment by kidsbear** [comment]
@jkhourybbn Hi, can you provide the test rigs that I can reproduce this error? Thanks~

**Comment by jkhourybbn** [comment]
Here is how to reproduce

Create example delta testrig by removing the following iptables rule from the example test rig test_rigs/example/iptables/host1.iptables
```
-A INPUT -p udp --dport 53 -j ACCEPT
```
Run batfish
```
init-testrig example
init-delta-testrig example_d
get nodes differential=true, summary=false
```

**Comment by kidsbear** [comment]
Thanks~ @jkhourybbn

**Comment by dhalperi** [comment]
proposal from in-person hacking:

```diff
diff --git a/projects/batfish/src/main/java/org/batfish/grammar/iptables/IptablesControlPlaneExtractor.java b/projects/batfish/src/main/java/org/batfish/grammar/iptables/IptablesControlPlaneExtractor.java
index 72ff8555f..c37afd218 100644
--- a/projects/batfish/src/main/java/org/batfish/grammar/iptables/IptablesControlPlaneExtractor.java
+++ b/projects/batfish/src/main/java/org/batfish/grammar/iptables/IptablesControlPlaneExtractor.java
@@ -187,6 +187,7 @@ public class IptablesControlPlaneExtractor extends IptablesParserBaseListener
       todo(ctx, "Unknown rule action");
     }
 
+    rule.setName(getFullText(ctx));
     return rule;
   }
 
@@ -225,6 +226,13 @@ public class IptablesControlPlaneExtractor extends IptablesParserBaseListener
     return null;
   }
 
+  private String getFullText(ParserRuleContext ctx) {
+    int start = ctx.getStart().getStartIndex();
+    int end = ctx.getStop().getStopIndex();
+    String text = _text.substring(start, end + 1);
+    return text;
+  }
+
   @Override
   public Set<String> getUnimplementedFeatures() {
     return _unimplementedFeatures;
diff --git a/projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesRule.java b/projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesRule.java
index 38e97ba7d..3ce027354 100644
--- a/projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesRule.java
+++ b/projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesRule.java
@@ -35,10 +35,11 @@ public class IptablesRule implements Serializable {
     }
   }
 
-  IptablesActionType _actionType;
-  List<IptablesMatch> _matchList;
+  private IptablesActionType _actionType;
+  private List<IptablesMatch> _matchList;
 
-  String _nextChain;
+  private String _nextChain;
+  private String _name;
 
   public IptablesRule() {
     _matchList = new LinkedList<>();
@@ -68,6 +69,10 @@ public class IptablesRule implements Serializable {
     return _matchList;
   }
 
+  public String getName() {
+    return _name;
+  }
+
   public String getNextChain() {
     return _nextChain;
   }
@@ -80,4 +85,8 @@ public class IptablesRule implements Serializable {
     _actionType = actionType;
     _nextChain = nextChain;
   }
+
+  public void setName(String name) {
+    this._name = name;
+  }
 }
diff --git a/projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesVendorConfiguration.java b/projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesVendorConfiguration.java
index b1c295559..6ce1f2aa1 100644
--- a/projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesVendorConfiguration.java
+++ b/projects/batfish/src/main/java/org/batfish/representation/iptables/IptablesVendorConfiguration.java
@@ -76,7 +76,7 @@ public class IptablesVendorConfiguration extends IptablesConfiguration {
   }
 
   private IpAccessList toIpAccessList(String aclName, IptablesChain chain) {
-    IpAccessList acl = new IpAccessList(aclName, new LinkedList<IpAccessListLine>());
+    IpAccessList acl = new IpAccessList(aclName, new LinkedList<>());
 
     for (IptablesRule rule : chain.getRules()) {
       IpAccessListLine aclLine = new IpAccessListLine();
@@ -92,11 +92,6 @@ public class IptablesVendorConfiguration extends IptablesConfiguration {
             List<SubRange> dstPortRanges = match.toPortRanges();
             aclLine.getDstPorts().addAll(dstPortRanges);
             break;
-            // case IN_INTERFACE:
-            // case OUT_INTERFACE:
-            // _warnings.unimplemented("Matching on incoming and outgoing
-            // interface not supported");
-            // break;
           case PROTOCOL:
             aclLine.getIpProtocols().add(match.toIpProtocol());
             break;
@@ -116,6 +111,7 @@ public class IptablesVendorConfiguration extends IptablesConfiguration {
       }
 
       aclLine.setAction(rule.getIpAccessListLineAction());
+      aclLine.setName(rule.getName());
       acl.getLines().add(aclLine);
     }
 
@@ -123,6 +119,7 @@ public class IptablesVendorConfiguration extends IptablesConfiguration {
     LineAction chainAction = chain.getIpAccessListLineAction();
     IpAccessListLine defaultLine = new IpAccessListLine();
     defaultLine.setAction(chainAction);
+    defaultLine.setName("default");
     acl.getLines().add(defaultLine);
 
     return acl;
```
