### ISSUE TITLE
pathDiff exception

### ISSUE THREAD

**Issue by jkhourybbn** [batfish/batfish#438]
If one tries to run the pathDiff reachability say using example test rig and example-with-delta
```
Caused by: org.batfish.common.BatfishException: Failed to deserialize object of type org.batfish.datamodel.Topology from file containers/cp_f3982773-b04e-437a-a9a5-8a33d191d4de/testrigs/tr_2a42ac7b-7708-4168-969d-21c8012d68fe/environments/env_default/env/env_topology
   at org.batfish.common.plugin.PluginConsumer.deserializeObject(PluginConsumer.java:115)
   at org.batfish.main.Batfish.loadTopology(Batfish.java:2624)
```

Looks like it tries to get a non-existent topology file. Is pathDiff not supported anymore, or am I not using it correctly?

**Comment by ratulm** [comment]
@jkhourybbn  - Can you report on the sequence of commands you used?

**Comment by jkhourybbn** [comment]
I couldn't find any documentation on this so i don't know how to use it. I essentially just initialized a rig and delta and invoked it (as with reduced). Can you briefly explain how to use it and what it is expected to do before I start looking at the code?

**Comment by ratulm** [comment]
I can repro ... looking into it.

**Comment by ratulm** [comment]
PR #440 addresses this issue. You can merge if you are blocked or wait for it to be merged into master.
