### ISSUE TITLE
NPE for smt-reachability

### ISSUE THREAD

**Issue by ratulm** [batfish/batfish#444]
batfish> init-testrig test_rigs/example
....
batfish> get smt-reachability 
Status: FAILURE
Question: reachability actions=[ACCEPT] | dstIps=[2.1.2.1]
org.batfish.common.BatfishException: Failed to answer question
   at org.batfish.main.Batfish.answer(Batfish.java:542)
   at org.batfish.main.Batfish.run(Batfish.java:3957)
   at org.batfish.main.Driver$1.run(Driver.java:327)
Caused by: java.lang.NullPointerException
   at com.microsoft.z3.Context.checkContextMatch(Context.java:3882)
   at com.microsoft.z3.Context.mkEq(Context.java:680)
   at org.batfish.smt.PropertyAdder.instrumentReachability(PropertyAdder.java:73)
   at org.batfish.smt.PropertyChecker.allReachable(PropertyChecker.java:64)
   at org.batfish.smt.PropertyChecker.computeReachability(PropertyChecker.java:109)
   at org.batfish.main.Batfish.smtReachability(Batfish.java:4597)
   at org.batfish.question.SmtReachabilityQuestionPlugin$ReachabilityAnswerer.answer(SmtReachabilityQuestionPlugin.java:30)
   at org.batfish.main.Batfish.answer(Batfish.java:539)
   ... 2 more
Summary: 0 (non-assertion) results;

**Comment by ratulm** [comment]
Another command, which seems to fail in a different place:

batfish> get smt-reachability finalNodeRegex="as2border1", finalIfaceRegex="Loopback.*"
Status: FAILURE
Question: reachability actions=[ACCEPT] | dstIps=[2.1.1.1]
org.batfish.common.BatfishException: Failed to answer question
   at org.batfish.main.Batfish.answer(Batfish.java:542)
   at org.batfish.main.Batfish.run(Batfish.java:3957)
   at org.batfish.main.Driver$1.run(Driver.java:327)
Caused by: java.lang.NullPointerException
   at org.batfish.smt.Encoder.lambda$null$9(Encoder.java:599)
   at java.util.HashMap.forEach(HashMap.java:1288)
   at org.batfish.smt.Encoder.lambda$buildCounterExample$10(Encoder.java:597)
   at java.util.HashMap.forEach(HashMap.java:1288)
   at org.batfish.smt.Encoder.buildCounterExample(Encoder.java:592)
   at org.batfish.smt.Encoder.verify(Encoder.java:789)
   at org.batfish.smt.PropertyChecker.computeReachability(PropertyChecker.java:143)
   at org.batfish.main.Batfish.smtReachability(Batfish.java:4597)
   at org.batfish.question.SmtReachabilityQuestionPlugin$ReachabilityAnswerer.answer(SmtReachabilityQuestionPlugin.java:30)
   at org.batfish.main.Batfish.answer(Batfish.java:539)
   ... 2 more
Summary: 0 (non-assertion) results;

**Comment by rabeckett** [comment]
The main issue seems to be that z3 can give "don't care" assignments to variables while the code expects an actual value.

**Comment by ratulm** [comment]
I see. 

Btw, you understand why is "dstIps=[2.1.1.1]" being shown as part of the question?  (Confusing because I never specified that IP.)
