### ISSUE TITLE
Cisco parser can't parse bgp neighbor 

### ISSUE THREAD

**Issue by nunoplopes** [batfish/batfish#475]
The following fails to parse with Batfish:

```
hostname foo

interface Ethernet0
  description bar

router bgp 42
  neighbor 10.0.0.1
    description foobar
    remote-as 33

   address-family ipv4
     neighbor 10.0.0.1 activate
```

Error:
```
parser: CiscoParser: line 7:2: no viable alternative at input 'neighbor'
Offending Token:  line 7:2  NEIGHBOR:'neighbor'  <== mode:DEFAULT_MODE
Error parsing top (leftmost) parser rule in stack: '[router_bgp_stanza_tail router_bgp_stanza stanza cisco_configuration]'.
Parse tree of current rule:
(router_bgp_stanza_tail)
Unconsumed tokens:
 line 7:2  NEIGHBOR:'neighbor'  <== mode:DEFAULT_MODE
 line 7:10 (HIDDEN)  M_NEIGHBOR_WS:' '  <== mode:M_NEIGHBOR
 line 7:11  IP_ADDRESS:'10.0.0.1'  <== mode:M_NEIGHBOR
 line 7:19  NEWLINE:'\n'  <== mode:DEFAULT_MODE
 line 8:0 (HIDDEN)  WS:'    '  <== mode:DEFAULT_MODE
 line 8:4  DESCRIPTION:'description'  <== mode:DEFAULT_MODE
 line 8:15  RAW_TEXT:' foobar'  <== mode:M_Description
 line 8:22  NEWLINE:'\n'  <== mode:M_Description
 line 9:0 (HIDDEN)  WS:'    '  <== mode:DEFAULT_MODE
 line 9:4  REMOTE_AS:'remote-as'  <== mode:DEFAULT_MODE
 line 9:13 (HIDDEN)  WS:' '  <== mode:DEFAULT_MODE
 line 9:14  DEC:'33'  <== mode:DEFAULT_MODE
 line 9:16  NEWLINE:'\n\n'  <== mode:DEFAULT_MODE
 line 11:0 (HIDDEN)  WS:'   '  <== mode:DEFAULT_MODE
 line 11:3  ADDRESS_FAMILY:'address-family'  <== mode:DEFAULT_MODE
 line 11:17 (HIDDEN)  WS:' '  <== mode:DEFAULT_MODE
 line 11:18  IPV4:'ipv4'  <== mode:DEFAULT_MODE
 line 11:22  NEWLINE:'\n'  <== mode:DEFAULT_MODE
 line 12:0 (HIDDEN)  WS:'     '  <== mode:DEFAULT_MODE
 line 12:5  NEIGHBOR:'neighbor'  <== mode:DEFAULT_MODE
 line 12:13 (HIDDEN)  M_NEIGHBOR_WS:' '  <== mode:M_NEIGHBOR
 line 12:14  IP_ADDRESS:'10.0.0.1'  <== mode:M_NEIGHBOR
 line 12:22 (HIDDEN)  WS:' '  <== mode:DEFAULT_MODE
 line 12:23  ACTIVATE:'activate'  <== mode:DEFAULT_MODE
 line 12:31  NEWLINE:'\n\n'  <== mode:DEFAULT_MODE
 line 14:0  EOF:<EOF>  <== mode:DEFAULT_MODE
Previous 10 tokens:
 line 4:2  DESCRIPTION:'description'  <== mode:DEFAULT_MODE
 line 4:13  RAW_TEXT:' bar'  <== mode:M_Description
 line 4:17  NEWLINE:'\n\n'  <== mode:M_Description
 line 6:0  ROUTER:'router'  <== mode:DEFAULT_MODE
 line 6:6 (HIDDEN)  WS:' '  <== mode:DEFAULT_MODE
 line 6:7  BGP:'bgp'  <== mode:DEFAULT_MODE
 line 6:10 (HIDDEN)  WS:' '  <== mode:DEFAULT_MODE
 line 6:11  DEC:'42'  <== mode:DEFAULT_MODE
 line 6:13  NEWLINE:'\n'  <== mode:DEFAULT_MODE
 line 7:0 (HIDDEN)  WS:'  '  <== mode:DEFAULT_MODE
Parser state info:
_cadant: false
_disableUnrecognized: false
_multilineBgpNeighbors: false

Error context lines:
   1:      hostname foo
   2:
   3:      interface Ethernet0
   4:        description bar
   5:
   6:      router bgp 42
>>>7:        neighbor 10.0.0.1
   8:          description foobar
   9:          remote-as 33
   10:
   11:        address-family ipv4
   12:          neighbor 10.0.0.1 activate
   13:
   14:

        at org.batfish.grammar.BatfishParserErrorListener.syntaxError(BatfishParserErrorListener.java:121)
        at org.batfish.grammar.BatfishParserErrorListener.syntaxError(BatfishParserErrorListener.java:136)
        at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
        at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:282)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:121)
        at org.batfish.grammar.cisco.CiscoParser.router_bgp_stanza_tail(CiscoParser.java)
        at org.batfish.grammar.cisco.CiscoParser.router_bgp_stanza(CiscoParser.java:65509)
        at org.batfish.grammar.cisco.CiscoParser.stanza(CiscoParser.java:24520)
        at org.batfish.grammar.cisco.CiscoParser.cisco_configuration(CiscoParser.java:2611)
        at org.batfish.grammar.cisco.CiscoCombinedParser.parse(CiscoCombinedParser.java:42)
        at org.batfish.grammar.cisco.CiscoCombinedParser.parse(CiscoCombinedParser.java:9)
        at org.batfish.main.Batfish.parse(Batfish.java:385)
        ... 6 more
```

**Comment by ratulm** [comment]
@nunoplopes  Based on the output trace, the error does not seem to be related to the address family. The address family appears on line 11; the parsing error is on line 7.  I've updated the title of the issue to reflect that. 

The router config you posted is legit -- what device/vendor does it correspond to? 

If its legit, can you help debug and/or send a PR? The relevant code is in Cisco_bgp.g4. If not, someone (probably @arifogel) will try to get to it soon.

**Comment by nunoplopes** [comment]
I believe the problem is triggered by address-family because it can appear in the context of router or neighbor. It's tricky to parse correctly :)  I guess Batfish parser trips because it sees neighbor -> address-family -> neighbor. But just guessing here.

This is a shortened version of a real config, yes.

**Comment by arifogel** [comment]
Sorry, but that doesn't look like a legal config to me. The `neighbor 10.0.0.1` is hierarchical like NX-OS, but then the activate line is flat like IOS.Batfish explicitly does not allow both flat and hierarchical neighbor statements in the same config. Can you confirm this was pulled from a live router? What OS?

**Comment by nunoplopes** [comment]
Ari, you're right. Sorry for the confusion.
I have to preprocess the files before shipping them to Batfish, and our printer was mixing up Arista and Cisco formats.
