### ISSUE TITLE
ios parser error (recovery broken) on bad interface name

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#4908]
```
bf.init_snapshot_from_text(
"""
!
hostname ios-bad-interface-name
!
interface bad-interface-name0
!
ip route 0.0.0.0 0.0.0.0 bad-interface-name0
!
interface all router disable
!
""",
    platform="cisco")
```

Will result in

```
java.lang.NullPointerException
	at org.batfish.grammar.cisco.CiscoControlPlaneExtractor.enterS_interface(CiscoControlPlaneExtractor.java:4369)
	at org.batfish.grammar.cisco.CiscoParser$S_interfaceContext.enterRule(CiscoParser.java)
	at org.batfish.grammar.BatfishParseTreeWalker.enterRule(BatfishParseTreeWalker.java:27)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.batfish.grammar.cisco.CiscoControlPlaneExtractor.processParseTree(CiscoControlPlaneExtractor.java:10685)
	at org.batfish.job.ParseVendorConfigurationJob.parseFile(ParseVendorConfigurationJob.java:336)
	at org.batfish.job.ParseVendorConfigurationJob.parse(ParseVendorConfigurationJob.java:405)
	at org.batfish.main.Batfish.getOrParse(Batfish.java:2516)
	at org.batfish.main.Batfish.lambda$serializeNetworkConfigs$49(Batfish.java:2579)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.batfish.main.Batfish.serializeNetworkConfigs(Batfish.java:2583)
	at org.batfish.main.Batfish.serializeVendorConfigs(Batfish.java:2749)
	at org.batfish.main.Batfish.run(Batfish.java:2160)
	at org.batfish.main.Driver.lambda$runBatfish$3(Driver.java:558)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

It looks like this is because `interface_name` is a crazy rule, in which the second half of the `|` does not require `name_prefix_alpha`.

@arifogel this looks like your domain.

cc: @agember from #4864

**Comment by dhalperi** [comment]
Or wait, maybe this is expected when we set `throwOnLexerError` as the test cases I'm seeing do. @agember were you running with that on? That is not normally on in runtime builds.

**Comment by dhalperi** [comment]
Ran it again correctly, still crashes. Stack trace updated, still @arifogel
