### ISSUE TITLE
getObject API returns 500, not 404 when API is called with invalid testrig name

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#554]
It's crashing rather than gracefully handling non-existent testrig:

```java
WMS:getObject exception: org.batfish.common.BatfishException: Testrig '2017-10-11_20:39:26' does not exist
	at org.batfish.coordinator.WorkMgr.getdirTestrig(WorkMgr.java:651)
	at org.batfish.coordinator.WorkMgr.getTestrigObject(WorkMgr.java:717)
	at org.batfish.coordinator.WorkMgrService.getObject(WorkMgrService.java:778)
	at sun.reflect.GeneratedMethodAccessor554.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by dhalperi** [comment]
obsolete for the v1 api
