### ISSUE TITLE
Cisco IOS-XR Route Policy parse error

### ISSUE THREAD

**Issue by oneryalcin** [batfish/batfish#5625]
Hi, 

My ASR 9K (IOS-XR) configs failed ingesting, and `bfq.initIssues().answer()` shows the following error:   

**Type**: `Parse Error`

**Line_Text**:
```
route-policy COUNTRY-COMPANY-REGION-IMPORT
  apply COMMUNITY-BASED-ROUTE-PREF-AS-ANY
  set extcommunity soo (64900:2)
end-policy
```
> Note: In the route policy above I changed the naming slightly to remove sensitive info

**Parser Context:**  `'[route_policy_stanza stanza cisco_xr_configuration]'`

**Details:**
```java
java.lang.NullPointerException
	at org.batfish.grammar.cisco_xr.CiscoXrControlPlaneExtractor.toExtcommunitySetRtExpr(CiscoXrControlPlaneExtractor.java:9116)
	at org.batfish.grammar.cisco_xr.CiscoXrControlPlaneExtractor.toRoutePolicyStatement(CiscoXrControlPlaneExtractor.java:9109)
	at org.batfish.grammar.cisco_xr.CiscoXrControlPlaneExtractor.toRoutePolicyStatement(CiscoXrControlPlaneExtractor.java:9101)
	at org.batfish.grammar.cisco_xr.CiscoXrControlPlaneExtractor.toRoutePolicyStatement(CiscoXrControlPlaneExtractor.java:9199)
	at org.batfish.grammar.cisco_xr.CiscoXrControlPlaneExtractor.toRoutePolicyStatement(CiscoXrControlPlaneExtractor.java:9086)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.batfish.grammar.cisco_xr.CiscoXrControlPlaneExtractor.toRoutePolicyStatementList(CiscoXrControlPlaneExtractor.java:9277)
	at org.batfish.grammar.cisco_xr.CiscoXrControlPlaneExtractor.enterRoute_policy_stanza(CiscoXrControlPlaneExtractor.java:2707)
	at org.batfish.grammar.cisco_xr.CiscoXrParser$Route_policy_stanzaContext.enterRule(CiscoXrParser.java)
	at org.batfish.grammar.BatfishParseTreeWalker.enterRule(BatfishParseTreeWalker.java:27)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.batfish.grammar.cisco_xr.CiscoXrControlPlaneExtractor.processParseTree(CiscoXrControlPlaneExtractor.java:7547)
	at org.batfish.job.ParseVendorConfigurationJob.parseFile(ParseVendorConfigurationJob.java:349)
	at org.batfish.job.ParseVendorConfigurationJob.parse(ParseVendorConfigurationJob.java:422)
	at org.batfish.main.Batfish.getOrParse(Batfish.java:2588)
	at org.batfish.main.Batfish.lambda$serializeNetworkConfigs$56(Batfish.java:2659)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
	at java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.batfish.main.Batfish.serializeNetworkConfigs(Batfish.java:2663)
	at org.batfish.main.Batfish.serializeVendorConfigs(Batfish.java:2831)
	at org.batfish.main.Batfish.run(Batfish.java:2215)
	at org.batfish.main.Driver.lambda$runBatfish$0(Driver.java:397)
	at java.lang.Thread.run(Thread.java:748)
```

I very much appreciate your help. 

Thanks a lot

**Comment by dhalperi** [comment]
@arifogel - the root of the issue here is

1. not parsing `soo`
2. recovery
3. converting route policies from outside-in.

2+3 is why we crash - it's never safe to recurse from a parent context to an inner context unless the grammar is perfect. Any advice on best next step?

**Comment by dhalperi** [comment]
Hey @oneryalcin - there is a new container with the workaround in #5636 released: `batfish:test-443` or `allinone:test-443` depending on what you use.

Would you mind trying it out and sending along the parse errors that seem most relevant? I suspect there are more things we need to handle - like `extcommunity-set soo`

**Comment by oneryalcin** [comment]
Hi @dhalperi 

I tested and it this time it didn't fail and successfully ingested the device. Thanks 

I have noticed few parsing warnings which caused few issues in my topology. 

If you think it's better to open separate issue for each, please let me know:

## **VRF Import Export failed:**

**Parse Warning**

```
{'Line': 122, 'Text': 'import route-target'},
 {'Line': 123, 'Text': '65001:58500'},
 {'Line': 125, 'Text': 'export route-policy SOME-POLICY'},
```

> For all lines Parser_Context is :
> ```
>  [vrfd_address_family s_vrf_definition stanza cisco_xr_configuration]
> ```


**Config**
```
vrf BSKYB-AWS-OTT
 address-family ipv4 unicast
  import route-target
   65001:58500
  !
  export route-policy SOME-POLICY
  ...
 !
!
```

 
## **IP Addressing parsing under `Bundle-Ethernet`s failed if no VRF defined**

:x: **If the Interface is Bundle-Ethernet  and no VRF is defined under the interface then it fails to recognize defined prefixes.
Parsing Error:**
```
 {'Line': 468, 'Text': 'ipv4 mtu 8192'},
 {'Line': 469, 'Text': 'ipv4 address 192.121.9.1 255.255.255.254'},
```

**Config:**
```
interface Bundle-Ether1
 ...
 mtu 8222
 ..
 ipv4 mtu 8192
 ipv4 address 1922.121.9.1 255.255.255.254
!
```

:white_check_mark: **But the prefix below is recognized successfully as VRF is defined under the interface**

```
interface Bundle-Ether13
 ...
 vrf Trusted-VRF
 ipv4 address 192.76.2.113 255.255.255.254
 ...
!
```

:white_check_mark: **A regular interface (no Bundle) is also successfully parsed even there is no VRF defined under.**

```
interface TenGigE0/8/1/3
 mtu 8222
 ipv4 mtu 8192
 ipv4 address 192.138.1.248 255.255.255.254
!
```


## `Prefix-Set` parsing failed
**This is a bit confusing as It failed for one prefix set and successfull for the rest**

```

{'Line': 906, 'Text': '192.168.0.0/20,', 'Parser_Context': '[extcommunity_set_rt s_extcommunity_set stanza cisco_xr_configuration]'},
{'Line': 907, 'Text': '192.168.126.0/23,', 'Parser_Context': '[cisco_xr_configuration]'},
  ... (there are 47 more prefixes here) 
{'Line': 954, 'Text': 'end-set', 'Parser_Context': '[cisco_xr_configuration]'},
```

**Config** 

```
prefix-set SOME-PREFIX
  192.168.0.0/20,
   ... <there are 48 more prefixes here> 
  192.168.126.0/23'
end-set
!
```

**Comment by dhalperi** [comment]
This is beautiful, thanks @oneryalcin .

Honestly things are a bit slowed down with the virus situation in Seattle, but we'll try to catch up.

**Comment by oneryalcin** [comment]
Thanks @dhalperi, I heard that Washington is one of the most affected states, hope it will recovers soon. It's pretty much same here in the UK, many restrictions. Virus is impacting whole world. 

Please let me know later, if you need anything else from my side.

**Comment by dhalperi** [comment]
I suspect most of these issues are now fixed at HEAD - we have forked off a new IOS-XR parser and reimplemented policies almost from scratch. Thanks for your patience!

Please open new issues if you run into this again.
