### ISSUE TITLE
Init error on Cisco ISR router

### ISSUE THREAD

**Issue by sriatom** [batfish/batfish#5997]
Exception:

java.lang.IllegalStateException: Invalid wildcard format for conversion to prefix: 65279
        at com.google.common.base.Preconditions.checkState(Preconditions.java:574)
        at org.batfish.datamodel.IpWildcard.toPrefix(IpWildcard.java:199)
        at org.batfish.representation.cisco.CiscoConversions.toRouteFilterLine(CiscoConversions.java:1606)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.batfish.representation.cisco.CiscoConversions.toRouteFilterList(CiscoConversions.java:1272)
        at org.batfish.representation.cisco.CiscoConfiguration.toVendorIndependentConfigurations(CiscoConfiguration.java:2938)
        at org.batfish.job.ConvertConfigurationJob.call(ConvertConfigurationJob.java:218)
        at org.batfish.job.ConvertConfigurationJob.call(ConvertConfigurationJob.java:38)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

[d-rtr01.zip](https://github.com/batfish/batfish/files/4928657/d-rtr01.zip)

**Comment by dhalperi** [comment]
Thanks for filing, @sriatom! It looks like batfish is being tripped up by lines like this in the access-list being used to match routes: `permit 172.16.0.0 0.0.254.255`. Note that the mask is not contigous. Which networks are actually matched by this line, do you know?

```
ip access-list standard REDIS-STATIC
 permit 172.16.0.0 0.0.254.255

route-map REDIS-EIGRP permit 10
 match ip address REDIS-STATIC

**Comment by sriatom** [comment]
I have fixed it Dan but I still get an exception. Is there any way I can run a validation myself on the config instead of opening a bug?

Attached the config
[d-rtr01.zip](https://github.com/batfish/batfish/files/4928720/d-rtr01.zip)

error
java.lang.IllegalStateException: Invalid wildcard format for conversion to prefix: 2303
        at com.google.common.base.Preconditions.checkState(Preconditions.java:574)
        at org.batfish.datamodel.IpWildcard.toPrefix(IpWildcard.java:199)
        at org.batfish.representation.cisco.CiscoConversions.toRouteFilterLine(CiscoConversions.java:1606)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.batfish.representation.cisco.CiscoConversions.toRouteFilterList(CiscoConversions.java:1272)
        at org.batfish.representation.cisco.CiscoConfiguration.toVendorIndependentConfigurations(CiscoConfiguration.java:2938)
        at org.batfish.job.ConvertConfigurationJob.call(ConvertConfigurationJob.java:218)
        at org.batfish.job.ConvertConfigurationJob.call(ConvertConfigurationJob.java:38)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by dhalperi** [comment]
Hey @sriatom - sorry for the hassle - the way I determined that was the problem line was a little indirect, and we need to make this better:

65279  = 0xFEFF = 0.0.254.255
2303 = 0x8FF = 0.0.8.255

This latter one is also not contiguous.

That's how you can self-diagnose for now, but obviously we need to make this code not crash.

**Comment by sriatom** [comment]
@dhalperi thanks Dan, I realized the other mess ups and fixed it. I am able to load it now. to identify such issues in other config, could I iterate through each row.Description and look for "IllegalStateException"?
