### ISSUE TITLE
iosxr - unable to init

### ISSUE THREAD

**Issue by sflowers0** [batfish/batfish#6302]
Entire config file fails to be ingested due to the below config:

```
extcommunity-set rt ABC
  12345:678910
end-set
!
```

Parse error:
```
Details
"java.lang.NullPointerException
    at org.batfish.grammar.cisco_xr.CiscoXrControlPlaneExtractor.lambda$enterExtcommunity_set_rt$3(CiscoXrControlPlaneExtractor.java:1859)
    at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
    at org.batfish.grammar.cisco_xr.CiscoXrControlPlaneExtractor.enterExtcommunity_set_rt(CiscoXrControlPlaneExtractor.java:1855)
    at org.batfish.grammar.cisco_xr.CiscoXrParser$Extcommunity_set_rtContext.enterRule(CiscoXrParser.java)
    at org.batfish.grammar.BatfishParseTreeWalker.enterRule(BatfishParseTreeWalker.java:27)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
    at org.batfish.grammar.cisco_xr.CiscoXrControlPlaneExtractor.processParseTree(CiscoXrControlPlaneExtractor.java:7546)
    at org.batfish.job.ParseVendorConfigurationJob.parseFile(ParseVendorConfigurationJob.java:368)
    at org.batfish.job.ParseVendorConfigurationJob.parse(ParseVendorConfigurationJob.java:442)
    at org.batfish.main.Batfish.getOrParse(Batfish.java:2505)
    at org.batfish.main.Batfish.lambda$serializeNetworkConfigs$48(Batfish.java:2580)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
    at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
    at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
    at java.util.stream.AbstractTask.compute(AbstractTask.java:327)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
"
```

**Comment by dhalperi** [comment]
Thanks @sflowers0 - taking a look.

Here's how I repro'd. In general, this is the best way to ship a bug report since you'll know we have full info (vs just subsetting configs).

```python
from pybatfish.client.session import Session
bf = Session.get()
bf.set_network('gh-6302')
text="""
extcommunity-set rt ABC
  12345:678910
end-set
!
"""

bf.init_snapshot_from_text(text=text, platform='cisco-xr')
```

```py
bf.q.fileParseStatus().answer()
```

```py
print(bf.q.initIssues().answer().frame().Details[0])
```
