### ISSUE TITLE
junos - multiple config files fail to be ingested

### ISSUE THREAD

**Issue by sflowers0** [batfish/batfish#6307]
```
Parse error "java.lang.NullPointerException
    at org.batfish.grammar.BatfishCombinedParser.getLine(BatfishCombinedParser.java:142)
    at org.batfish.common.ErrorDetails$ParseExceptionContext.<init>(ErrorDetails.java:95)
    at org.batfish.grammar.BatfishParseTreeWalker.exitRule(BatfishParseTreeWalker.java:53)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:30)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
    at org.batfish.grammar.flatjuniper.PreprocessJuniperExtractor.preprocess(PreprocessJuniperExtractor.java:129)
    at org.batfish.grammar.flatjuniper.FlatJuniperControlPlaneExtractor.processParseTree(FlatJuniperControlPlaneExtractor.java:37)
    at org.batfish.job.ParseVendorConfigurationJob.parseFile(ParseVendorConfigurationJob.java:368)
    at org.batfish.job.ParseVendorConfigurationJob.parse(ParseVendorConfigurationJob.java:442)
    at org.batfish.main.Batfish.getOrParse(Batfish.java:2505)
    at org.batfish.main.Batfish.lambda$serializeNetworkConfigs$48(Batfish.java:2580)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
    at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
    at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
    at java.util.stream.AbstractTask.compute(AbstractTask.java:327)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
"
```

Out of 256 config files, only 4 were completely parsed and produced results (just looking for orphan config structures).

**Comment by ratulm** [comment]
@sflowers0 - can you share a few of the configs that produce this exception? the exception itself does not contain enough information. there is likely a common (simple) fix here. 

you may use https://github.com/intentionet/netconan to anonymize configs and/or share the configs via Slack DM.

**Comment by sflowers0** [comment]
configs were shared on slack

**Comment by dhalperi** [comment]
Thanks @sflowers0 - and sorry it took so long for us to get to this. Thanks for pinging!
