### ISSUE TITLE
Dataplane generation fails on IPSec topology builder

### ISSUE THREAD

**Issue by dalrrard** [batfish/batfish#6478]
When generating the dataplane for a network, a failure occurs in the IPSec topology builder when the following conditions are true in the structure definition of the tunnel interface:

`'destinationAddress': 'AUTO/NONE(-1l)'` & `'localAddress': 'AUTO/NONE(-1l)'`

This is failing on valid configurations that are using `tunnel mode gre multipoint` in the tunnel interface, have an `address 0.0.0.0 0.0.0.0` in the crypto ikev2 keyring, a `match identity remote address 0.0.0.0` in the crypto ikev2 profile, and where the tunnel is using a source interface that is either set to DHCP or is a Cellular interface that has no IP address by design.

The error states that self-loops are not allowed during the graph generation, but I imagine that the desired result is that these peer configurations should just be ignored when building the IPSec topology or Batfish should give a different answer to the local or destination address when the above conditions are met. 

Let me know if you need any more info, and I can supply some pared down configuration snippets that cause this.

```
Exception in container:b8274e4e-4927-4293-82de-4135d5068006, testrig:6d256a07-f3d9-4b6d-babb-e19ec33183c7; exception:com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Cannot add self-loop edge on node org.batfish.datamodel.IpsecPeerConfigId@83df94d6, as self-loops are not allowed. To construct a graph that allows self-loops, call allowsSelfLoops(true) on the Builder.
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3976)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4960)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4966)
	at org.batfish.topology.TopologyProviderImpl.getInitialIpsecTopology(TopologyProviderImpl.java:61)
	at org.batfish.dataplane.ibdp.IncrementalDataPlanePlugin.computeDataPlane(IncrementalDataPlanePlugin.java:32)
	at org.batfish.main.Batfish.computeDataPlane(Batfish.java:740)
	at org.batfish.main.Batfish.run(Batfish.java:2098)
	at org.batfish.main.Driver.lambda$runBatfish$0(Driver.java:312)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Cannot add self-loop edge on node org.batfish.datamodel.IpsecPeerConfigId@83df94d6, as self-loops are not allowed. To construct a graph that allows self-loops, call allowsSelfLoops(true) on the Builder.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
	at com.google.common.graph.ConfigurableMutableValueGraph.putEdgeValue(ConfigurableMutableValueGraph.java:82)
	at org.batfish.common.util.IpsecUtil.lambda$initIpsecTopology$1(IpsecUtil.java:135)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at com.google.common.collect.CollectSpliterators$FlatMapSpliterator.lambda$forEachRemaining$1(CollectSpliterators.java:361)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at com.google.common.collect.CollectSpliterators$FlatMapSpliterator.forEachRemaining(CollectSpliterators.java:357)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at org.batfish.common.util.IpsecUtil.initIpsecTopology(IpsecUtil.java:115)
	at org.batfish.common.topology.TopologyUtil.computeIpsecTopology(TopologyUtil.java:562)
	at org.batfish.topology.TopologyProviderImpl.computeInitialIpsecTopology(TopologyProviderImpl.java:277)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 10 more
```

**Comment by dhalperi** [comment]
@dalrrard thanks - this is a great bug report.

I think a pared down configuration might be helpful, but I can try and take a look next week either way.

If interested, find me on Batfish slack - same username :)

**Comment by corinaminer** [comment]
@dalrrard We just merged #6581, which may fix your issue. Your guess was correct:
> these peer configurations should just be ignored when building the IPSec topology

IPSec topology now ignores tunnels where we can't determine the local address (meaning `localAddress` would be `AUTO/NONE(-1l)`). Although, your reported condition raises the question of whether we also need to explicitly ignore tunnels where we can't determine the destination address... 🤔 

Would it be possible for you to check your network again to see if this failure still happens? If you're using Docker, you won't have the change yet, but we can update this issue when we release an updated Docker image.
