### ISSUE TITLE
bf_generate_dataplane fails on NeighborIsAsPath

### ISSUE THREAD

**Issue by racsoce** [batfish/batfish#6510]
doing bf_generate_dataplane fails:

BatfishException: Work terminated abnormally
work_item: {"containerName": "online", "id": "d8a0b920-05ca-48fd-91c6-1d99a0cad272", "requestParams": {"dp": "", "testrig": "online"}, "testrigName": "online"}

log: Loading configurations for NetworkSnapshot{network=618aa744-b3f6-414e-8d7f-3115cd46ebd4, snapshot=719dc039-90ee-4964-a148-6b4f32634e2b}
Loading configurations for NetworkSnapshot{network=618aa744-b3f6-414e-8d7f-3115cd46ebd4, snapshot=719dc039-90ee-4964-a148-6b4f32634e2b}
Loading configurations for NetworkSnapshot{network=618aa744-b3f6-414e-8d7f-3115cd46ebd4, snapshot=719dc039-90ee-4964-a148-6b4f32634e2b}
Loading configurations for NetworkSnapshot{network=618aa744-b3f6-414e-8d7f-3115cd46ebd4, snapshot=719dc039-90ee-4964-a148-6b4f32634e2b}
Exception in container:618aa744-b3f6-414e-8d7f-3115cd46ebd4, testrig:719dc039-90ee-4964-a148-6b4f32634e2b; exception:org.batfish.common.BatfishException: No implementation for NeighborIsAsPath.evaluate()
	at org.batfish.datamodel.routing_policy.expr.NeighborIsAsPath.evaluate(NeighborIsAsPath.java:46)
	at org.batfish.datamodel.routing_policy.statement.If.execute(If.java:107)
	at org.batfish.datamodel.routing_policy.RoutingPolicy.call(RoutingPolicy.java:118)
	at org.batfish.datamodel.routing_policy.RoutingPolicy.process(RoutingPolicy.java:241)
	at org.batfish.datamodel.routing_policy.RoutingPolicy.processBgpRoute(RoutingPolicy.java:223)
	at org.batfish.dataplane.ibdp.BgpRoutingProcess.pullV4UnicastMessages(BgpRoutingProcess.java:686)
	at org.batfish.dataplane.ibdp.BgpRoutingProcess.processBgpV4UnicastMessages(BgpRoutingProcess.java:595)
	at org.batfish.dataplane.ibdp.BgpRoutingProcess.processBgpMessages(BgpRoutingProcess.java:487)
	at org.batfish.dataplane.ibdp.BgpRoutingProcess.executeIteration(BgpRoutingProcess.java:407)
	at org.batfish.dataplane.ibdp.VirtualRouter.bgpIteration(VirtualRouter.java:1331)
	at org.batfish.dataplane.ibdp.IncrementalBdpEngine.lambda$null$15(IncrementalBdpEngine.java:434)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405)
	at org.batfish.dataplane.ibdp.IncrementalBdpEngine.lambda$computeIterationOfBgpRoutes$16(IncrementalBdpEngine.java:434)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
{"answerElements":[{"class":"org.batfish.common.BatfishException$BatfishStackTrace","answer":["org.batfish.common.BatfishException: No implementation for NeighborIsAsPath.evaluate()","   at org.batfish.datamodel.routing_policy.expr.NeighborIsAsPath.evaluate(NeighborIsAsPath.java:46)","   at org.batfish.datamodel.routing_policy.statement.If.execute(If.java:107)","   at org.batfish.datamodel.routing_policy.RoutingPolicy.call(RoutingPolicy.java:118)","   at org.batfish.datamodel.routing_policy.RoutingPolicy.process(RoutingPolicy.java:241)","   at org.batfish.datamodel.routing_policy.RoutingPolicy.processBgpRoute(RoutingPolicy.java:223)","   at org.batfish.dataplane.ibdp.BgpRoutingProcess.pullV4UnicastMessages(BgpRoutingProcess.java:686)","   at org.batfish.dataplane.ibdp.BgpRoutingProcess.processBgpV4UnicastMessages(BgpRoutingProcess.java:595)","   at org.batfish.dataplane.ibdp.BgpRoutingProcess.processBgpMessages(BgpRoutingProcess.java:487)","   at org.batfish.dataplane.ibdp.BgpRoutingProcess.executeIteration(BgpRoutingProcess.java:407)","   at org.batfish.dataplane.ibdp.VirtualRouter.bgpIteration(VirtualRouter.java:1331)","   at org.batfish.dataplane.ibdp.IncrementalBdpEngine.lambda$null$15(IncrementalBdpEngine.java:434)","   at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405)","   at org.batfish.dataplane.ibdp.IncrementalBdpEngine.lambda$computeIterationOfBgpRoutes$16(IncrementalBdpEngine.java:434)","   at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)","   at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)","   at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)","   at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)","   at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)","   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)","   at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)","   at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)","   at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)",""]}],"status":"FAILURE","summary":{"numFailed":0,"numPassed":0,"numResults":0}}

**Comment by racsoce** [comment]
adding bf_upload_diagnostics files:
[batfish_diag.zip](https://github.com/batfish/batfish/files/5699057/batfish_diag.zip)

**Comment by ratulm** [comment]
@racsoce - Digging a bit through the trace, what is unsupported is `as-path passes-through` in XR policy. You might be able to make progress by deleting/editing that bit. Though I do see a bunch of other unsupported stuff in the diagnostic files.

**Comment by racsoce** [comment]
@ratulm thanks, after a deep debug I found one line in 2 MX480:

set routing-instances xxx protocols bgp group xxx neighbor xx.xx.xx.xx

after removing the 2 lines the 'bf_generate_dataplane()' gets done, very slow (00:05:04 elapsed) but we can query for routes now,

wondering how I can help you to identify and solve root cause.

Thanks,

**Comment by ratulm** [comment]
Hmm....that is different from my expectation. 

Does the MX peer with XR using the line you deleted? That is, the neighbor on that deleted line is an XR router with `as-path passes-through` clause.

**Comment by racsoce** [comment]
Both neighbors are cisco ASR9K with the following:

 !
 neighbor xx.xx.xx.xx.
  remote-as xxxxx
  description xxxxx
  address-family ipv4 unicast
   route-policy iad1-v4-in in
   route-policy iad1-v4-out out
   next-hop-self
   soft-reconfiguration inbound always
  !
!
route-policy iad1-v4-in
  if as-path neighbor-is 'xxxxx'  then
    set community (xxxxx:200)
    pass
  endif
end-policy
!
!
route-policy iad1-v4-out
  if destination in default-v4 then
    pass
  endif
end-policy
!

**Comment by ratulm** [comment]
aha, the likely culprit is  `if as-path neighbor-is 'xxxxx' then` -- deleting those lines or expressing it differently will let you keep the bgp session up and compute routes.

**Comment by dhalperi** [comment]
This is fully implemented at HEAD. THanks for your patience, @racsoce !
