### ISSUE TITLE
Device hostname starting with a digit causes the batfish to fail

### ISSUE THREAD

**Issue by armartirosyan** [batfish/batfish#6966]
If the device's hostname starts with a digit (e.g. `2901-SW1`) then the below error is being thrown. 
```
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.8.3/bin/network-importer", line 8, in <module>
    sys.exit(main())
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/network_importer/cli.py", line 146, in check
    ni.init(limit=limit)
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/network_importer/performance.py", line 67, in timed
    result = method(*args, **kw)
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/network_importer/main.py", line 136, in init
    self.network.load()
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/network_importer/adapters/network_importer/adapter.py", line 64, in load
    if len(self.bfi.q.nodeProperties(nodes=hostname).answer()) == 0:
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pybatfish/question/question.py", line 192, in answer
    return _bf_answer_obj(
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pybatfish/client/internal.py", line 50, in _bf_answer_obj
    resthelper.get_json_response(
  File "/home/user/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pybatfish/client/resthelper.py", line 79, in get_json_response
    raise BatfishException(
pybatfish.exception.BatfishException: Coordinator returned failure: Invalid question network-importer/__nodeProperties_789b67a2-12f3-4902-9557-c3e00a7d58a2: Could not parse JSON question: Cannot construct instance of `org.batfish.question.nodeproperties.NodePropertiesQuestion`, problem: Error parsing '2901-SW1' as nodeSpecifier after index 0. Valid continuations are NODE_SET_OP.. See https://pybatfish.readthedocs.io/en/latest/specifiers.html#node-specifier for valid grammar.
 at [Source: (String)"{"class":"org.batfish.question.nodeproperties.NodePropertiesQuestion","differential":false,"instance":{"description":"Returns configuration settings of nodes.","instanceName":"__nodeProperties_789b67a2-12f3-4902-9557-c3e00a7d58a2","longDescription":"Lists global settings of devices in the network. Settings that are specific to interfaces, routing protocols, etc. are available via other questions.","orderedVariableNames":["nodes","properties"],"tags":["configuration"],"variables":{"nodes":{"descr"[truncated 298 chars]; line: 1, column: 798]
```

**Comment by ratulm** [comment]
You need to wrap names that begin with digits in quotes, so, something like `nodes="\"2901-SW1\""`

Relevant documentation is here: https://pybatfish.readthedocs.io/en/latest/specifiers.html#general-notes-on-the-grammar

PS: If you are on Slack, it is a better place for such questions. https://join.slack.com/t/batfish-org/shared_invite/enQtMzA0Nzg2OTAzNzQ1LTcyYzY3M2Q0NWUyYTRhYjdlM2IzYzRhZGU1NWFlNGU2MzlhNDY3OTJmMDIyMjQzYmRlNjhkMTRjNWIwNTUwNTQ Someone can unblock you a lot faster.
