### ISSUE TITLE
AWS VpcPeeringConnections parser error

### ISSUE THREAD

**Issue by saparikh** [batfish/batfish#705]
If the VpcPeeringConnections-<region>.json file has a stanza for Acceptor and Requestor VPC info, which is missing the CidrBlock entry

   "CidrBlock": "10.194.0.0/16", 
    "CidrBlockSet": [
     {
      "CidrBlock": "10.194.0.0/16"
     }

then it fails. This scenario could arise if the VpcPeeringConnection was deleted (as shown below):

{
   "AccepterVpcInfo": {
    "OwnerId": "118292266645", 
    "VpcId": "vpc-6ee90d17"
   }, 
   "RequesterVpcInfo": {
    "OwnerId": "118292266645", 
    "VpcId": "vpc-56c5212f"
   }, 
   "Status": {
    "Code": "deleted", 
    "Message": "Deleted by 118292266645"
   },

**Comment by saparikh** [comment]
The error message seen is:

org.batfish.common.BatfishException: Problems parsing JSON in /home/samir/git/barclays-demo/containers/LHR/testrigs/master_2017-12-06-22:20:17_655a652/testrig/aw
s_configs/VpcPeeringConnections-us-west-2.json
	at org.batfish.main.Batfish.parseAwsVpcConfigurations(Batfish.java:2793)
	at org.batfish.main.Batfish.serializeAwsVpcConfigs(Batfish.java:3910)
	at org.batfish.main.Batfish.serializeVendorConfigs(Batfish.java:4202)
	at org.batfish.main.Batfish.run(Batfish.java:3845)
	at org.batfish.main.Driver$1.run(Driver.java:356)
Caused by: org.codehaus.jettison.json.JSONException: JSONObject["CidrBlock"] not found.
	at org.codehaus.jettison.json.JSONObject.get(JSONObject.java:407)
	at org.codehaus.jettison.json.JSONObject.getString(JSONObject.java:543)
	at org.batfish.representation.aws_vpcs.VpcPeeringConnection.<init>(VpcPeeringConnection.java:28)
	at org.batfish.representation.aws_vpcs.AwsVpcConfiguration.addConfigElement(AwsVpcConfiguration.java:139)
	at org.batfish.representation.aws_vpcs.AwsVpcConfiguration.addConfigElement(AwsVpcConfiguration.java:78)
	at org.batfish.main.Batfish.parseAwsVpcConfigurations(Batfish.java:2791)
	... 4 more
{
  "answerElements" : [
    {
      "class" : "org.batfish.common.BatfishException$BatfishStackTrace",
      "answer" : [
        "org.batfish.common.BatfishException: Batfish job failed",
        "   at org.batfish.main.Driver$1.run(Driver.java:384)",
        "Caused by: org.batfish.common.BatfishException: Problems parsing JSON in /home/samir/git/barclays-demo/containers/LHR/testrigs/master_2017-12-06-22:20:1
7_655a652/testrig/aws_configs/VpcPeeringConnections-us-west-2.json",
        "   at org.batfish.main.Batfish.parseAwsVpcConfigurations(Batfish.java:2793)",
        "   at org.batfish.main.Batfish.serializeAwsVpcConfigs(Batfish.java:3910)",
        "   at org.batfish.main.Batfish.serializeVendorConfigs(Batfish.java:4202)",
        "   at org.batfish.main.Batfish.run(Batfish.java:3845)",
        "   at org.batfish.main.Driver$1.run(Driver.java:356)",
        "Caused by: org.codehaus.jettison.json.JSONException: JSONObject[\"CidrBlock\"] not found.",
        "   at org.codehaus.jettison.json.JSONObject.get(JSONObject.java:407)",
        "   at org.codehaus.jettison.json.JSONObject.getString(JSONObject.java:543)",
        "   at org.batfish.representation.aws_vpcs.VpcPeeringConnection.<init>(VpcPeeringConnection.java:28)",
        "   at org.batfish.representation.aws_vpcs.AwsVpcConfiguration.addConfigElement(AwsVpcConfiguration.java:139)",
        "   at org.batfish.representation.aws_vpcs.AwsVpcConfiguration.addConfigElement(AwsVpcConfiguration.java:78)",
        "   at org.batfish.main.Batfish.parseAwsVpcConfigurations(Batfish.java:2791)",
        "   ... 4 more"
      ]
    }
  ],
  "status" : "FAILURE",
  "summary" : {
    "numFailed" : 0,
    "numPassed" : 0,
    "numResults" : 0
  }
}
