### ISSUE TITLE
Cisco NXOS Failed to queue work: Cannot queue dataplane dependent work

### ISSUE THREAD

**Issue by Ar4w** [batfish/batfish#7274]
Hello!
Can't parse my configs. I'm getting the next traceback

```
>>> r = bfq.routes().answer().frame()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pybatfish/question/question.py", line 200, in answer
    extra_args=extra_args,
  File "/usr/local/lib/python3.6/site-packages/pybatfish/client/internal.py", line 58, in _bf_answer_obj
    workhelper.execute(work_item, session, background, extra_args)
  File "/usr/local/lib/python3.6/site-packages/pybatfish/client/workhelper.py", line 107, in execute
    session, CoordConsts.SVC_RSC_QUEUE_WORK, json_data
  File "/usr/local/lib/python3.6/site-packages/pybatfish/client/resthelper.py", line 78, in get_json_response
    "Coordinator returned failure: {}".format(json_response[1])
pybatfish.exception.BatfishException: Coordinator returned failure: Failed to queue work: Cannot queue dataplane dependent work for 07d81203-fba8-4215-ac02-27292aa01d51: Status is DATAPLANING_FAIL but no incomplete dataplaning work exists
>>> 

```
Could you please help?

I've tried bf_generate_dataplane() with the next result.

```
>>> bf_generate_dataplane()
status: TRYINGTOASSIGN
.... no task information
status: CHECKINGSTATUS
.... 2021-08-27 02:05:22.975000-04:00 Begin job.
status: TERMINATEDABNORMALLY
.... 2021-08-27 02:05:22.975000-04:00 Begin job.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pybatfish/client/commands.py", line 248, in bf_generate_dataplane
    return bf_session.generate_dataplane(snapshot=snapshot, extra_args=extra_args)
  File "/usr/local/lib/python3.6/site-packages/pybatfish/client/session.py", line 667, in generate_dataplane
    answer_dict = workhelper.execute(work_item, self, extra_args=extra_args)
  File "/usr/local/lib/python3.6/site-packages/pybatfish/client/workhelper.py", line 152, in execute
    prefix="..." if log_file_msg else "",
pybatfish.exception.BatfishException: Work terminated abnormally
work_item: {"containerName": "test", "id": "6009892b-cb1f-4b4b-ab13-d2b3a9643652", "requestParams": {"dp": "", "testrig": "test3"}, "testrigName": "test3"}

log: Loading configurations for NetworkSnapshot{network=48225384-b61d-4644-9266-e16edc5cbd2c, snapshot=07d81203-fba8-4215-ac02-27292aa01d51}
Loading configurations for NetworkSnapshot{network=48225384-b61d-4644-9266-e16edc5cbd2c, snapshot=07d81203-fba8-4215-ac02-27292aa01d51}
Loading configurations for NetworkSnapshot{network=48225384-b61d-4644-9266-e16edc5cbd2c, snapshot=07d81203-fba8-4215-ac02-27292aa01d51}
Loading configurations for NetworkSnapshot{network=48225384-b61d-4644-9266-e16edc5cbd2c, snapshot=07d81203-fba8-4215-ac02-27292aa01d51}
Loading configurations for NetworkSnapshot{network=48225384-b61d-4644-9266-e16edc5cbd2c, snapshot=07d81203-fba8-4215-ac02-27292aa01d51}
Exception in container:48225384-b61d-4644-9266-e16edc5cbd2c, testrig:07d81203-fba8-4215-ac02-27292aa01d51; exception:java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:492)
	at org.batfish.datamodel.routing_policy.statement.SetEigrpMetric.execute(SetEigrpMetric.java:65)
	at org.batfish.datamodel.routing_policy.statement.If.execute(If.java:113)
	at org.batfish.datamodel.routing_policy.RoutingPolicy.call(RoutingPolicy.java:121)
	at org.batfish.datamodel.routing_policy.expr.CallExpr.evaluate(CallExpr.java:66)
	at org.batfish.datamodel.routing_policy.statement.If.execute(If.java:106)
	at org.batfish.datamodel.routing_policy.RoutingPolicy.call(RoutingPolicy.java:121)
	at org.batfish.datamodel.routing_policy.expr.CallExpr.evaluate(CallExpr.java:66)
	at org.batfish.datamodel.routing_policy.statement.If.execute(If.java:106)
	at org.batfish.datamodel.routing_policy.statement.If.execute(If.java:113)
	at org.batfish.datamodel.routing_policy.RoutingPolicy.call(RoutingPolicy.java:121)
	at org.batfish.datamodel.routing_policy.RoutingPolicy.process(RoutingPolicy.java:289)
	at org.batfish.datamodel.routing_policy.RoutingPolicy.process(RoutingPolicy.java:212)
	at org.batfish.dataplane.ibdp.OspfRoutingProcess.convertToExternalRoute(OspfRoutingProcess.java:1425)
	at org.batfish.dataplane.ibdp.OspfRoutingProcess.lambda$computeRedistributionDelta$28(OspfRoutingProcess.java:1139)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.batfish.dataplane.ibdp.OspfRoutingProcess.computeRedistributionDelta(OspfRoutingProcess.java:1142)
	at org.batfish.dataplane.ibdp.OspfRoutingProcess.redistribute(OspfRoutingProcess.java:324)
	at org.batfish.dataplane.ibdp.VirtualRouter.lambda$redistribute$39(VirtualRouter.java:1501)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at com.google.common.collect.CollectSpliterators$FlatMapSpliterator.lambda$forEachRemaining$1(CollectSpliterators.java:361)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at com.google.common.collect.CollectSpliterators$FlatMapSpliterator.forEachRemaining(CollectSpliterators.java:357)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.batfish.dataplane.ibdp.VirtualRouter.redistribute(VirtualRouter.java:1501)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.batfish.dataplane.ibdp.IncrementalBdpEngine.computeNonMonotonicPortionOfDataPlane(IncrementalBdpEngine.java:679)
	at org.batfish.dataplane.ibdp.IncrementalBdpEngine.computeDataPlane(IncrementalBdpEngine.java:240)
	at org.batfish.dataplane.ibdp.IncrementalDataPlanePlugin.computeDataPlane(IncrementalDataPlanePlugin.java:46)
	at org.batfish.main.Batfish.computeDataPlane(Batfish.java:813)
	at org.batfish.main.Batfish.run(Batfish.java:2204)
	at org.batfish.main.Driver.lambda$runBatfish$0(Driver.java:312)
	at java.base/java.lang.Thread.run(Thread.java:834)
{"answerElements":[{"class":"org.batfish.common.BatfishException$BatfishStackTrace","answer":["org.batfish.common.BatfishException: Batfish job failed","   at org.batfish.main.Driver.lambda$runBatfish$0(Driver.java:352)","   at java.base/java.lang.Thread.run(Thread.java:834)","Caused by: java.lang.IllegalStateException","   at com.google.common.base.Preconditions.checkState(Preconditions.java:492)","   at org.batfish.datamodel.routing_policy.statement.SetEigrpMetric.execute(SetEigrpMetric.java:65)","   at org.batfish.datamodel.routing_policy.statement.If.execute(If.java:113)","   at org.batfish.datamodel.routing_policy.RoutingPolicy.call(RoutingPolicy.java:121)","   at org.batfish.datamodel.routing_policy.expr.CallExpr.evaluate(CallExpr.java:66)","   at org.batfish.datamodel.routing_policy.statement.If.execute(If.java:106)","   at org.batfish.datamodel.routing_policy.RoutingPolicy.call(RoutingPolicy.java:121)","   at org.batfish.datamodel.routing_policy.expr.CallExpr.evaluate(CallExpr.java:66)","   at org.batfish.datamodel.routing_policy.statement.If.execute(If.java:106)","   at org.batfish.datamodel.routing_policy.statement.If.execute(If.java:113)","   at org.batfish.datamodel.routing_policy.RoutingPolicy.call(RoutingPolicy.java:121)","   at org.batfish.datamodel.routing_policy.RoutingPolicy.process(RoutingPolicy.java:289)","   at org.batfish.datamodel.routing_policy.RoutingPolicy.process(RoutingPolicy.java:212)","   at org.batfish.dataplane.ibdp.OspfRoutingProcess.convertToExternalRoute(OspfRoutingProcess.java:1425)","   at org.batfish.dataplane.ibdp.OspfRoutingProcess.lambda$computeRedistributionDelta$28(OspfRoutingProcess.java:1139)","   at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)","   at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)","   at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)","   at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)","   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)","   at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)","   at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)","   at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)","   at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)","   at org.batfish.dataplane.ibdp.OspfRoutingProcess.computeRedistributionDelta(OspfRoutingProcess.java:1142)","   at org.batfish.dataplane.ibdp.OspfRoutingProcess.redistribute(OspfRoutingProcess.java:324)","   at org.batfish.dataplane.ibdp.VirtualRouter.lambda$redistribute$39(VirtualRouter.java:1501)","   at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)","   at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)","   at com.google.common.collect.CollectSpliterators$FlatMapSpliterator.lambda$forEachRemaining$1(CollectSpliterators.java:361)","   at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)","   at com.google.common.collect.CollectSpliterators$FlatMapSpliterator.forEachRemaining(CollectSpliterators.java:357)","   at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)","   at org.batfish.dataplane.ibdp.VirtualRouter.redistribute(VirtualRouter.java:1501)","   at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)","   at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)","   at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)","   at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)","   at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)","   at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)","   at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)","   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)","   at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)","   at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)","   at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)","   at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)","   at org.batfish.dataplane.ibdp.IncrementalBdpEngine.computeNonMonotonicPortionOfDataPlane(IncrementalBdpEngine.java:679)","   at org.batfish.dataplane.ibdp.IncrementalBdpEngine.computeDataPlane(IncrementalBdpEngine.java:240)","   at org.batfish.dataplane.ibdp.IncrementalDataPlanePlugin.computeDataPlane(IncrementalDataPlanePlugin.java:46)","   at org.batfish.main.Batfish.computeDataPlane(Batfish.java:813)","   at org.batfish.main.Batfish.run(Batfish.java:2204)","   at org.batfish.main.Driver.lambda$runBatfish$0(Driver.java:312)","   ... 1 more",""]}],"status":"FAILURE","summary":{"numFailed":0,"numPassed":0,"numResults":0}}
>>> 

```
Thank you in advance

**Comment by ratulm** [comment]
@Ar4w - since it is an error with the route simulation, individual configs or config sections will not be enough. You could run your configs through https://github.com/intentionet/netconan to anonymize, which will strip out IPs, passwords, and keys.
