### ISSUE TITLE
NoSuchMethodError: org.batfish.datamodel.BgpRoute$Builder.setOriginType

### ISSUE THREAD

**Issue by nunoplopes** [batfish/batfish#753]
When running `batfish -dp true -env env_default -jobs 1 -testrig foo -containerdir .` I get the following error:

```*** COMPUTING DATA PLANE ***
java.lang.NoSuchMethodError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
        at org.batfish.bdp.BdpEngine.computeDependentRoutesIteration(BdpEngine.java:596)
        at org.batfish.bdp.BdpEngine.computeFixedPoint(BdpEngine.java:737)
        at org.batfish.bdp.BdpEngine.computeDataPlane(BdpEngine.java:416)
        at org.batfish.bdp.BdpDataPlanePlugin.computeDataPlane(BdpDataPlanePlugin.java:48)
        at org.batfish.main.Batfish.computeDataPlane(Batfish.java:869)
        at org.batfish.main.Batfish.run(Batfish.java:3874)
        at org.batfish.main.Driver$1.run(Driver.java:356)
Caused by: java.lang.NoSuchMethodError: org.batfish.datamodel.BgpRoute$Builder.setOriginType(Lorg/batfish/datamodel/OriginType;)V
        at org.batfish.datamodel.routing_policy.statement.SetOrigin.execute(SetOrigin.java:50)
        at org.batfish.datamodel.routing_policy.expr.WithEnvironmentExpr.evaluate(WithEnvironmentExpr.java:106)
        at org.batfish.datamodel.routing_policy.expr.Conjunction.evaluate(Conjunction.java:60)
        at org.batfish.datamodel.routing_policy.expr.Disjunction.evaluate(Disjunction.java:60)
        at org.batfish.datamodel.routing_policy.statement.If.execute(If.java:89)
        at org.batfish.datamodel.routing_policy.RoutingPolicy.call(RoutingPolicy.java:99)
        at org.batfish.datamodel.routing_policy.expr.CallExpr.evaluate(CallExpr.java:83)
        at org.batfish.datamodel.routing_policy.statement.If.execute(If.java:89)
        at org.batfish.datamodel.routing_policy.RoutingPolicy.call(RoutingPolicy.java:99)
        at org.batfish.datamodel.routing_policy.RoutingPolicy.process(RoutingPolicy.java:163)
        at org.batfish.bdp.VirtualRouter.propagateBgpRoutes(VirtualRouter.java:1369)
        at org.batfish.bdp.BdpEngine.lambda$computeDependentRoutesIteration$11(BdpEngine.java:599)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2897)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by arifogel** [comment]
I would be very surprised if this is due to anything other than stale binaries. Does this occur using a fresh repository?

**Comment by dhalperi** [comment]
Aka, run `batfish_rebuild_all` or, more directly, `mvn -f projects/pom.xml
clean package`
