### ISSUE TITLE
Nexus: redistribute command parsed incorrectly

### ISSUE THREAD

**Issue by nunoplopes** [batfish/batfish#800]
The following snippet crashes Batfish:
```
router bgp 42
  neighbor 1.2.3.4
    remote-as 8075
    route-map MAP1 in
  address-family ipv4 unicast
    redistribute direct route-map MAP2
    neighbor 1.2.3.4 activate
  exit
```

Error:
```
        org.batfish.common.BatfishException: Error post-processing parse tree of configuration file: 'foo.txt'
        at org.batfish.job.ParseVendorConfigurationJob.call(ParseVendorConfigurationJob.java:331)
        at org.batfish.job.ParseVendorConfigurationJob.call(ParseVendorConfigurationJob.java:32)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.batfish.common.BatfishException: do not currently handle per-neighbor redistribution policies
        at org.batfish.grammar.cisco.CiscoControlPlaneExtractor.exitRedistribute_connected_bgp_tail(CiscoControlPlaneExtractor.java:4813)
        at org.batfish.grammar.cisco.CiscoParser$Redistribute_connected_bgp_tailContext.exitRule(CiscoParser.java)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:47)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:30)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.batfish.grammar.cisco.CiscoControlPlaneExtractor.processParseTree(CiscoControlPlaneExtractor.java:6293)
        at org.batfish.job.ParseVendorConfigurationJob.call(ParseVendorConfigurationJob.java:307)
```

According to https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus7000/sw/unicast/command/reference/n7k_unicast_cmds/l3_cmds_r.html the redistribute command's context is only AF or router.
Even though the AF command could have been parsed in the context of neighbor instead of router, the redistribute command belongs clearly to the router context.
Gotta love these ambiguous grammars... :)

**Comment by dhalperi** [comment]
We rewrote the NX-OS BGP parser and it is now on by default. A large class of bugs like this one is no fixed. Thanks for filing, @nunoplopes !
