### ISSUE TITLE
OutOfMemoryError for seemingly simple configuration

### ISSUE THREAD

**Issue by mxsasha** [batfish/batfish#8166]
I am running into a reproducible OutOfMemoryError for a config I am analysing. I have narrowed this down to a small snippet, listed below, which looks like a trivial configuration to me. Curiously, removing any single line from that config resolves the error. Even stranger, some changes, but not all, to the prefix lists resolve the error. For example, changing `pl_ours` to contain `1.1.0.0/22` and `1.2.0.0/22` resolves the issue.

This is my current configuration, which triggers the error:
```
set groups re0 system host-name router
set policy-options prefix-list pl_bogon 0.0.0.0/8
set policy-options prefix-list pl_bogon 10.0.0.0/8
set policy-options prefix-list pl_bogon 100.64.0.0/10
set policy-options prefix-list pl_bogon 127.0.0.0/8
set policy-options prefix-list pl_bogon 169.254.0.0/16
set policy-options prefix-list pl_bogon 172.16.0.0/12
set policy-options prefix-list pl_bogon 192.0.0.0/24
set policy-options prefix-list pl_bogon 192.0.2.0/24
set policy-options prefix-list pl_bogon 192.168.0.0/16
set policy-options prefix-list pl_bogon 198.18.0.0/15
set policy-options prefix-list pl_bogon 198.51.100.0/24
set policy-options prefix-list pl_bogon 203.0.113.0/24
set policy-options prefix-list pl_bogon 224.0.0.0/4
set policy-options prefix-list pl_ours 1.2.4.0/22
set policy-options prefix-list pl_ours 1.4.36.0/22
set policy-options policy-statement ps_ebgp_in term bogons-ipv4 from prefix-list-filter pl_bogon orlonger
set policy-options policy-statement ps_ebgp_in term bogons-ipv4 then reject
set policy-options policy-statement ps_ebgp_in term our-ipv4 from prefix-list-filter pl_ours orlonger
set policy-options policy-statement ps_ebgp_in term our-ipv4 then reject
set policy-options policy-statement ps_ebgp_in term max-length from route-filter 0.0.0.0/0 prefix-length-range /25-/32
set policy-options policy-statement ps_ebgp_in term max-length then community add cm_no_export
set policy-options community cm_no_export members 65000:1
```

My code that produces the error is:
```
from pybatfish.client.session import Session
from pybatfish.datamodel import BgpRouteConstraints

bf = Session(host="localhost")

bf.set_network('example')
bf.init_snapshot('snap', name='snap', overwrite=True)
bf.q.searchRoutePolicies(policies="ps_ebgp_in", inputConstraints=BgpRouteConstraints(prefix=["17.16.0.0/16"]), action="permit").answer().frame()
```

Which results in:
```
log: Loading configurations for NetworkSnapshot{network=827377d6-be2c-4190-a4e0-d140e4ce3280, snapshot=d713627d-f480-4ece-aaa9-f75d32013f24}
Loading configurations for NetworkSnapshot{network=827377d6-be2c-4190-a4e0-d140e4ce3280, snapshot=d713627d-f480-4ece-aaa9-f75d32013f24}
Loading configurations for NetworkSnapshot{network=827377d6-be2c-4190-a4e0-d140e4ce3280, snapshot=d713627d-f480-4ece-aaa9-f75d32013f24}
Loading configurations for NetworkSnapshot{network=827377d6-be2c-4190-a4e0-d140e4ce3280, snapshot=d713627d-f480-4ece-aaa9-f75d32013f24}
Exception in container:827377d6-be2c-4190-a4e0-d140e4ce3280, testrig:d713627d-f480-4ece-aaa9-f75d32013f24; exception:java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
        at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
        at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538)
        at java.base/java.lang.StringBuffer.append(StringBuffer.java:317)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1663)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)
        at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)
        at net.sf.javabdd.BDD.toString(BDD.java:1646)
{"answerElements":[{"class":"org.batfish.common.BatfishException$BatfishStackTrace","answer":["org.batfish.common.BatfishException: Batfish job failed","   at org.batfish.main.Driver.lambda$runBatfish$0(Driver.java:303)","   at java.base/java.lang.Thread.run(Thread.java:829)","Caused by: java.lang.OutOfMemoryError: Java heap space","   at java.base/java.util.Arrays.copyOf(Arrays.java:3745)","   at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)","   at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538)","   at java.base/java.lang.StringBuffer.append(StringBuffer.java:317)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1663)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1675)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)","   at net.sf.javabdd.BDD.bdd_printset_rec(BDD.java:1680)","   at net.sf.javabdd.BDD.toString(BDD.java:1646)",""]}],"status":"FAILURE","summary":{"numFailed":0,"numPassed":0,"numResults":0}}
```

I am using image ID fb3cd1840fbe, pybatfish 0.0.2.

**Comment by dhalperi** [comment]
@millstein is on vacation, taking a look.
