### ISSUE TITLE
"Unsupported integer update" on localpref substraction

### ISSUE THREAD

**Issue by mxsasha** [batfish/batfish#8172]
My query is:
```
bf.q.searchRoutePolicies(policies="modify_localpref", inputConstraints=BgpRouteConstraints(prefix=["172.16.0.0/16"]), action="permit").answer().frame()
```

The following statement:
```
set policy-options policy-statement modify_localpref term lower-pref then local-preference subtract 25
```

Will cause this exception:
```
Exception in container:827377d6-be2c-4190-a4e0-d140e4ce3280, testrig:1997d6e3-f7e8-4dd9-85f3-d2243930c523; exception:org.batfish.common.QuestionException: Exception answering question
        at org.batfish.datamodel.answers.Answer.append(Answer.java:46)
        at org.batfish.main.Batfish.run(Batfish.java:2227)
        at org.batfish.main.Driver.lambda$runBatfish$0(Driver.java:263)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.batfish.common.BatfishException: Failed to answer question
        at org.batfish.main.Batfish.answer(Batfish.java:658)
        ... 3 more
Caused by: org.batfish.common.BatfishException: Unsupported features in route policy modify_localpref in node nodename
        at org.batfish.minesweeper.question.searchroutepolicies.SearchRoutePoliciesAnswerer.searchPolicy(SearchRoutePoliciesAnswerer.java:496)
        at org.batfish.minesweeper.question.searchroutepolicies.SearchRoutePoliciesAnswerer.lambda$searchPoliciesForNode$5(SearchRoutePoliciesAnswerer.java:536)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2739)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.batfish.minesweeper.question.searchroutepolicies.SearchRoutePoliciesAnswerer.answer(SearchRoutePoliciesAnswerer.java:549)
        at org.batfish.main.Batfish.answer(Batfish.java:655)
        ... 3 more
Caused by: java.lang.IllegalArgumentException: Unsupported integer update: org.batfish.datamodel.routing_policy.expr.DecrementLocalPreference@19
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
        at org.batfish.minesweeper.bdd.TransferBDD.applyLongExprModification(TransferBDD.java:173)
        at org.batfish.minesweeper.bdd.TransferBDD.compute(TransferBDD.java:642)
        at org.batfish.minesweeper.bdd.TransferBDD.compute(TransferBDD.java:724)
        at org.batfish.minesweeper.bdd.TransferBDD.compute(TransferBDD.java:714)
        at org.batfish.minesweeper.bdd.TransferBDD.compute(TransferBDD.java:724)
        at org.batfish.minesweeper.bdd.TransferBDD.compute(TransferBDD.java:557)
        at org.batfish.minesweeper.bdd.TransferBDD.compute(TransferBDD.java:724)
        at org.batfish.minesweeper.bdd.TransferBDD.compute(TransferBDD.java:736)
        at org.batfish.minesweeper.bdd.TransferBDD.compute(TransferBDD.java:1167)
        at org.batfish.minesweeper.question.searchroutepolicies.SearchRoutePoliciesAnswerer.searchPolicy(SearchRoutePoliciesAnswerer.java:490)
        ... 22 more
```

The origin seems to me to be [here](https://github.com/batfish/batfish/blob/ecbe8a219cecef65ad1b1bb20b5d5713a0ea3a38/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L173) but beyond that I don't know enough to debug this - 25 should be a valid long, to the best of my Java knowledge. And [DecrementLocalPreference](https://github.com/batfish/batfish/blob/ecbe8a219cecef65ad1b1bb20b5d5713a0ea3a38/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/DecrementLocalPreference.java#L45-L57) suggests that there is a built-in default.

Therefore, my first guess is that this is a parsing error in Batfish. But, if this is just not supported, it would be good if Batfish offers a way to still process supported parts of the policy - the only other workaround now is to comment out these statements manually.

**Comment by dhalperi** [comment]
To set expectations, `searchRoutePolicies` is alpha-ware and has several gaps.

**Comment by dhalperi** [comment]
I suspect this code you almost linked to is highlighting that this was just never implemented:

https://github.com/batfish/batfish/blob/ecbe8a219cecef65ad1b1bb20b5d5713a0ea3a38/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L178-L180

**Comment by millstein** [comment]
localpref subtraction is still not supported by SearchRoutePolicies, but the recent Batfish PR #8228 makes it so that unhandled features are simply ignored (and a warning is logged), which allows the analysis to continue.  Any results returned by the analysis are guaranteed to be correct, because they ignore executions that can reach unhandled features.  However, the presence of unhandled features could cause the analysis to miss results that should be returned.
