### ISSUE TITLE
Unable to run the batfish with args "-loglevel debug -batfishmode workservice -runmode interactive -coordinatorargs "-templatedirs questions""

### ISSUE THREAD

**Issue by nidinlal** [batfish/batfish#8216]
I am able to run the batfish with the following args "-runmode interactive -loglevel debug -batfishmode workservice -runclient false -coordinatorargs "-templatedirs questions""
But when i remove the arg "-runclient false" it's giving me the following error:

Started client with args: [-loglevel, debug, -runmode, interactive, -tracingenable, false]
Starting coordinator with args: [-templatedirs, questions, -tracingenable, false]
Starting batfish worker with args: [-runmode, WORKSERVICE, -register, true, -coordinatorpoolport, 9998, -tracingenable, false]
Using authorizer NoneAuthorizer
Starting server at http://localhost:9995
Starting pool manager at http://localhost:9998
BF-Client: unable to connect to coordinator at http://localhost:9997/batfishworkmgr/
Exeption while checking reachability to coordinator: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:284)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:753)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:752)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:419)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:319)
	at org.batfish.client.BfCoordWorkHelper.isReachable(BfCoordWorkHelper.java:420)
	at org.batfish.client.Client.initHelpers(Client.java:1764)
	at org.batfish.client.Client.run(Client.java:2536)
	at org.batfish.allinone.AllInOne.run(AllInOne.java:131)
	at org.batfish.allinone.Main.main(Main.java:6)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
	at java.net.Socket.connect(Socket.java:606)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1240)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1167)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1061)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:995)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1584)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1512)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:390)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:282)
	... 14 more

Process finished with exit code 1

I am running the batfish in IntelliJ on Mac M1 laptop?

**Comment by arifogel** [comment]
It's possible that M1 is not currently supported, but just in case the issue is only with your configuration, read the following:

Interactive mode is not supported, and only exists to support some legacy tests. You should use an external client like pybatfish for e2e testing, or just use unit tests for internal testing.

Here are my (bazel project) run settings in Intellij for `allinone`:
Target expression:
```
//projects/allinone:allinone_with_minesweeper_main
```
Bazel flags (both jvm options below are optional. Make a `log4j2.properties` file if you want to configure logging):
```
--jvmopt=-Xmx20g
--jvmopt=-Dlog4j2.configurationFile=/home/arifogel/git/batfish/log4j2.properties
```
Executable flags (replace `/home/arifogel/git/batfish` with the path to your clone of `batfish`, or use a relative dir or intellij variables to avoid providing a fixed absolute path):
```
-runclient
false
-coordinatorargs
'-templatedirs /home/arifogel/git/batfish/questions -containerslocation /home/arifogel/git/batfish/containers'
```
Here are the contents of my  my `log4j2.properties` file. You can customize to your liking:
```
appender.console.type=Console
appender.console.name=STDOUT
appender.console.layout.type=PatternLayout
# loglevel, line number, message newline
appender.console.layout.pattern=%p %l %m%n
logger.bflogger.name=org.batfish.common.BatfishLogger
logger.bflogger.level=warn
logger.bflogger.additivity=false
logger.bflogger.appenderRef.stdout.ref=STDOUT
# Update this to whatever log level you desire while debugging tests
rootLogger.level=info
rootLogger.appenderRef.stdout.ref=STDOUT
```
