### ISSUE TITLE
Data plane generation for example-juniper testrig throws NullPointer exception

### ISSUE THREAD

**Issue by haverma** [batfish/batfish#827]
Steps to reproduce:
In Batfish Java client, run
1. `init-testrig test_rigs/example-juniper`
2. run `generate-dataplane`

this will produce the stacktrace:
`Caused by: java.lang.NullPointerException
   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
   at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
   at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
   at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
   at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
   at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
   at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
   at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
   at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
   at org.batfish.bdp.BdpEngine.computeDependentRoutesIteration(BdpEngine.java:646)
   at org.batfish.bdp.BdpEngine.computeFixedPoint(BdpEngine.java:810)
   at org.batfish.bdp.BdpEngine.computeDataPlane(BdpEngine.java:425)
   at org.batfish.bdp.BdpDataPlanePlugin.computeDataPlane(BdpDataPlanePlugin.java:50)
   at org.batfish.main.Batfish.computeDataPlane(Batfish.java:898)
   at org.batfish.main.Batfish.run(Batfish.java:3751)
   at org.batfish.main.Driver$1.run(Driver.java:368)`

**Comment by haverma** [comment]
Fixed by PR #862
