### ISSUE TITLE
Fix failing java-smt assertions 

### ISSUE THREAD

**Issue by anothermattbrown** [batfish/batfish#829]
Running the java-smt (Minesweeper) tests with assertions fails:

```
$ ALLINONE_JAVA_ARGS="$ALLINONE_JAVA_ARGS -enableassertions" allinone -cmdfile tests/java-smt/commands 2>&1 | grep Test:
Test: 'get smt-forwarding dstIps=["42.42.42.0"], fullModel=True' matches tests/java-smt/bgp1-forwarding.ref: Fail
Test: 'get smt-reachability finalNodeRegex="R1", finalIfaceRegex="Loopback.*", fullModel=True' matches tests/java-smt/bgp1-reachability.ref: Fail
Test: 'get smt-bounded-length finalNodeRegex="R1", finalIfaceRegex="Loopback.*", bound=1, fullModel=True' matches tests/java-smt/bgp1-bounded-len.ref: Fail
Test: 'get smt-bounded-length finalNodeRegex="R1", finalIfaceRegex="Loopback.*", bound=0, fullModel=True' matches tests/java-smt/bgp1-bounded-len2.ref: Fail
Test: 'get smt-routing-loop fullModel=True' matches tests/java-smt/bgp1-routing-loop.ref: Fail
Test: 'get smt-multipath-consistency finalNodeRegex="R1", finalIfaceRegex="Loopback.*", fullModel=True' matches tests/java-smt/bgp1-multipath.ref: Fail
Test: 'get smt-forwarding dstIps=["70.70.70.70"], fullModel=True' matches tests/java-smt/ospf3-forward.ref: Pass
Test: 'get smt-reachability finalNodeRegex="R3", finalIfaceRegex="Loopback.*", fullModel=True' matches tests/java-smt/ospf3-reachable.ref: Pass
Test: 'get smt-bounded-length finalNodeRegex="R3", finalIfaceRegex="Loopback.*", bound=2, fullModel=True' matches tests/java-smt/ospf3-bounded-len.ref: Pass
Test: 'get smt-bounded-length finalNodeRegex="R3", finalIfaceRegex="Loopback.*", bound=1, fullModel=True' matches tests/java-smt/ospf3-bounded-len2.ref: Pass
Test: 'get smt-equal-length finalNodeRegex="R3", finalIfaceRegex="Loopback.*", ingressNodeRegex="R(1|2)", fullModel=True' matches tests/java-smt/ospf3-equal-len.ref: Pass
Test: 'get smt-equal-length finalNodeRegex="R3", finalIfaceRegex="Loopback.*", ingressNodeRegex="R(1|0)", fullModel=True' matches tests/java-smt/ospf3-equal-len2.ref: Pass
Test: 'get smt-routing-loop fullModel=True' matches tests/java-smt/ospf3-routing-loop.ref: Pass
Test: 'get smt-multipath-consistency finalNodeRegex="R3", finalIfaceRegex="Loopback.*", fullModel=True' matches tests/java-smt/ospf3-multipath.ref: Pass
Test: 'get smt-deterministic' matches tests/java-smt/ospf3-deterministic.ref: Pass
Test: 'get smt-forwarding dstIps=["192.168.8.3"], fullModel=True' matches tests/java-smt/ospf-cost.ref: Fail
Test: 'get smt-local-consistency nodeRegex=".*", fullModel=True' matches tests/java-smt/env2-local.ref: Fail
Test: 'get smt-local-consistency nodeRegex="", fullModel=True' matches tests/java-smt/env2-local2.ref: Pass
Test: 'get smt-forwarding dstIps=["172.0.0.0"], fullModel=True' matches tests/java-smt/static2-forward.ref: Pass
Test: 'get smt-routing-loop fullModel=True' matches tests/java-smt/static2-loop.ref: Pass
Test: 'get smt-reachability ingressNodeRegex="host1", finalNodeRegex="host3"' matches tests/java-smt/static3-reachability1.ref: Pass
Test: 'get smt-reachability ingressNodeRegex="host1", finalNodeRegex="host3", dstIps=["192.168.8.2"]' matches tests/java-smt/static3-reachability2.ref: Pass
Test: 'get smt-reachability ingressNodeRegex="host1", finalNodeRegex="host3", dstIps=["192.168.8.1"]' matches tests/java-smt/static3-reachability3.ref: Pass
Test: 'get smt-forwarding dstIps=["69.69.69.0"], fullModel=True' matches tests/java-smt/bgp3-forwarding1.ref: Fail
Test: 'get smt-forwarding dstIps=["42.42.42.0"], fullModel=True' matches tests/java-smt/bgp3-forwarding2.ref: Fail
Test: 'get smt-forwarding dstIps=["70.70.70.70"], fullModel=True' matches tests/java-smt/redistribute1-forwarding1.ref: Pass
Test: 'get smt-forwarding dstIps=["69.69.69.0"], fullModel=True' matches tests/java-smt/redistribute1-forwarding2.ref: Fail
Test: 'get smt-forwarding dstIps=["180.0.0.0"], fullModel=True' matches tests/java-smt/redistribute1-forwarding3.ref: Fail
Test: 'get smt-forwarding dstIps=["140.0.0.0"], fullModel=True' matches tests/java-smt/redistribute1-forwarding4.ref: Fail
Test: 'get smt-forwarding dstIps=["70.70.70.70"], fullModel=True' matches tests/java-smt/ospf1-forwarding.ref: Pass
Test: 'get smt-forwarding dstIps=["70.70.70.70"], fullModel=True' matches tests/java-smt/ospf2-forwarding.ref: Pass
Test: 'get smt-forwarding dstIps=["70.70.70.70"], fullModel=True' matches tests/java-smt/ospf4-forwarding.ref: Pass
Test: 'get smt-forwarding dstIps=["41.41.41.1"], fullModel=True' matches tests/java-smt/prepend1-forwarding.ref: Fail
Test: 'get smt-forwarding dstIps=["42.42.42.0"]' matches tests/java-smt/stable3-forwarding.ref: Fail
Test: 'get smt-deterministic' matches tests/java-smt/stable3-nondeterministic.ref: Fail
Test: 'get smt-forwarding dstIps=["41.41.41.1"], fullModel=True' matches tests/java-smt/overflow1-forwarding.ref: Fail
Test: 'get smt-forwarding dstIps=["70.70.70.70"], fullModel=True' matches tests/java-smt/area1-forwarding.ref: Pass
Test: 'get smt-forwarding dstIps=["42.42.42.1"], fullModel=True' matches tests/java-smt/aggregation1-forwarding.ref: Fail
Test: 'get smt-forwarding dstIps=["42.42.42.1"], fullModel=True' matches tests/java-smt/aggregation2-forwarding.ref: Fail
Test: 'get smt-local-consistency fullModel=True, minimize=True' matches tests/java-smt/env3-local.ref: Fail
Test: 'get smt-forwarding dstIps=["70.70.70.70"], fullModel=True' matches tests/java-smt/acl1-forwarding.ref: Pass
Test: 'get smt-multipath-consistency finalNodeRegex="R3", finalIfaceRegex="Loopback.*", fullModel=True' matches tests/java-smt/acl1-multipath.ref: Pass
Test: 'get smt-reachability diffType=any, failures=1, failNode1Regex="R2", failNode2Regex="R3"' matches tests/java-smt/acl1-differential1.ref: Pass
Test: 'get smt-reachability diffType=reduced, failures=1, failNode1Regex="R0", failNode2Regex="R1"' matches tests/java-smt/acl1-differential2.ref: Pass
Test: 'get smt-reachability diffType=increased, failures=1' matches tests/java-smt/acl1-differential3.ref: Pass
Test: 'get smt-forwarding dstIps=["20.20.20.20"], fullModel=True, baseEnvType=none' matches tests/java-smt/ibgp1-forwarding.ref: Pass
Test: 'get smt-forwarding dstIps=["4.4.4.4"], fullModel=True, baseEnvType=none' matches tests/java-smt/ibgp2-forwarding.ref: Fail
Test: 'get smt-forwarding dstIps=["4.4.4.4"], fullModel=True, baseEnvType=none' matches tests/java-smt/ibgp3-forwarding.ref: Fail
Test: 'get smt-forwarding dstIps=["42.42.42.1"], fullModel=True' matches tests/java-smt/community1.ref: Fail
Test: 'get smt-reachability ingressNodeRegex="as2border.*", finalNodeRegex="as2dept1", finalIfaceRegex="FastEthernet1/0" , failures=0' matches tests/java-smt/campus2-reachability1.ref: Fail
Test: 'get smt-reachability ingressNodeRegex="as2border.*", finalNodeRegex="as2dept1", finalIfaceRegex="FastEthernet1/0" , failures=1' matches tests/java-smt/campus2-reachability2.ref: Fail
Test: 'get smt-reachability finalNodeRegex="R3", finalIfaceRegex="Loopback.*", failures=1, diffType=any, dstIps=["70.70.70.70"]' matches tests/java-smt/differential1.ref: Pass
Test: 'get smt-reachability finalNodeRegex="R3", finalIfaceRegex="Loopback.*", failures=2, diffType=any, ingressNodeRegex="R0", failNode1Regex="R0", dstIps=["70.70.70.70"]' matches tests/java-smt/differential2.ref: Pass
Test: 'get smt-roles equivType=policy' matches tests/java-smt/roles1.ref: Pass
```

Here's the failing assertion for each failing test (the assertion location follows the corresponding ref file name):
```
$ for f in tests/java-smt/*.ref; do if [ -e $f.testout ]; then echo $f; diff $f $f.testout | grep AssertionError -A1 | tail -n1; fi; done
tests/java-smt/acl1-forwarding.ref
tests/java-smt/acl1-multipath.ref
tests/java-smt/aggregation1-forwarding.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/aggregation2-forwarding.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/area1-forwarding.ref
tests/java-smt/bgp1-bounded-len.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/bgp1-bounded-len2.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/bgp1-forwarding.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/bgp1-multipath.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/bgp1-reachability.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/bgp1-routing-loop.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/bgp3-forwarding1.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/bgp3-forwarding2.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/campus2-reachability1.ref
>         "   at org.batfish.symbolic.TransferResult.mergeChangedVariables(TransferResult.java:66)",
tests/java-smt/campus2-reachability2.ref
>         "   at org.batfish.symbolic.TransferResult.mergeChangedVariables(TransferResult.java:66)",
tests/java-smt/community1.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/env2-local.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/env3-local.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/ibgp2-forwarding.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/ibgp3-forwarding.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/ospf-cost.ref
>         "   at org.batfish.symbolic.TransferResult.mergeChangedVariables(TransferResult.java:66)",
tests/java-smt/ospf1-forwarding.ref
tests/java-smt/ospf2-forwarding.ref
tests/java-smt/ospf3-bounded-len2.ref
tests/java-smt/ospf3-equal-len2.ref
tests/java-smt/ospf3-forward.ref
tests/java-smt/ospf4-forwarding.ref
tests/java-smt/overflow1-forwarding.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/prepend1-forwarding.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/redistribute1-forwarding1.ref
tests/java-smt/redistribute1-forwarding2.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/redistribute1-forwarding3.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/redistribute1-forwarding4.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/stable3-forwarding.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/stable3-nondeterministic.ref
>         "   at org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)",
tests/java-smt/static2-forward.ref
tests/java-smt/static2-loop.ref
```

**Comment by anothermattbrown** [comment]
@rabeckett said the following regarding the error `org.batfish.symbolic.smt.EncoderSlice.isRelevantFor(EncoderSlice.java:454)`:

> The assertion failure appears to just be checking that the prefix filter is well-formed:
> `assert (p.getPrefixLength() < lower && lower <= upper);`
> It may be the case that this should actually be:
> `assert (p.getPrefixLength() <= lower && lower <= upper);`
> When I wrote this, I believe I was using [this site](http://packetlife.net/blog/2010/feb/1/understanding-ip-prefix-lists/) as a reference.

**Comment by dhalperi** [comment]
There seems to be another bug in that we're not testing with assertions enabled.

Either:
* don't use `assert`, use something else that is run in normal execution
* or turn on `assert` during tests?

**Comment by anothermattbrown** [comment]
It appears that all `assert`s in batfish are in minesweeper code. Does batfish use another mechanism for assertions? If yes, then we should migrate minesweepers to that.

**Comment by anothermattbrown** [comment]
After discussing with @arifogel, it sounds like the thing to do wrt `assert`s is to enable them during testing and use them when appropriate. We can decide whether Minesweeper's assertions should be `assert` or if/throw separately.

**Comment by anothermattbrown** [comment]
Here's my current understanding of the failing assertion at `org.batfish.symbolic.TransferResult.mergeChangedVariables(TransferResult.java:66)`:

- This part of minesweeper is based on SSA in compilers. We have something like an if-then-else, where the two branches are expected to set/constrain the same set of variables. The merge function is pairing up the variables in the two branches, so a phi function can later equate them.
- The problem is that we have a few test cases where the two branches do not set/constrain the same set of variables. This causes the assertion failure. When assertions are disabled, this results in `null` pointers in the pairing. The implementation of phi function (`TransferSSA.joinPoint`) checks for `null` in the pairing, so it looks like the assertion is unnecessary. This would explain why these tests pass with assertions disabled.

I recommend removing this assertion.
