### ISSUE TITLE
Cannot construct a next hop when missing both a next hop IP and interface

### ISSUE THREAD

**Issue by pawelhaj** [batfish/batfish#8298]
Hello, 

I get the following error for below configuration:

Convert error,"java.lang.IllegalArgumentException: Cannot construct a next hop when missing both a next hop IP and interface
	at org.batfish.datamodel.route.nh.NextHop.legacyConverter(NextHop.java:46)
	at org.batfish.representation.juniper.JuniperConfiguration.toStaticRoutes(JuniperConfiguration.java:3186)
	at org.batfish.representation.juniper.JuniperConfiguration.toVendorIndependentConfiguration(JuniperConfiguration.java:3606)
	at org.batfish.representation.juniper.JuniperConfiguration.toVendorIndependentConfigurations(JuniperConfiguration.java:3244)
	at org.batfish.job.ConvertConfigurationJob.call(ConvertConfigurationJob.java:801)
	at org.batfish.job.ConvertConfigurationJob.call(ConvertConfigurationJob.java:99)

```
routing-instances {
    VR-MGMT {
        instance-type virtual-router;
        interface ae53.104;
        interface ae54.104;
        interface irb.104;
        routing-options {
            static {
                route 0.0.0.0/0 {
                    qualified-next-hop 10.93.31.12;
                    qualified-next-hop 10.93.31.14;
                }
            }
        }
    }
}
```

**Comment by pawelhaj** [comment]
Is is a correct router configuration ? Has anyone encountered this problem ?
