### ISSUE TITLE
Running Tiramisu-batfish failed

### ISSUE THREAD

**Issue by maming-seu** [batfish/batfish#8702]
**Sir, i tried a tool based on batfish which names Tiramisu, it did the same things as batfish but in a different way**. **However it run into error when i tried its example. The auther didn't maintain his software and i cant even get content with him**. **So i thought mabye i can get some help from you guys.**  

Here follows the README in his porject:

```
First you need to create a cmdfile (lets call it testc) with the following format

init-snapshot <path_to_config_folder>
get arcRAG failNodeRegex="<ip-files>", notFailNodeRegex="<policy>"

<path_to_config_folder> is the physical path which has your network data (e.g. batfish/tests/java-smt/networks/BGP1 ). This folder should have a subfolder called configs which has all the device configuration files.
<ip-files> is a file with a set of srcIps, dstIps that we will use to verify the policy (e.g., batfish/testcom).
Depending on the requirement, you can use the following <policy>:
block - always blocked
tpvp - currently reachable, (just run an instance of tpvp to find a path between src and dst)
fail - always reachable < K fails (it computes the value of K to cause unreachability)
Then in bash, you can run the command allinone -cmdfile <cmdfile_name> (e.g. allinone -cmdfile testc)
```

In ```BGP1``` there are two files which are both router's configuration, and in testcom it writes ```smt-reachability srcIps=["42.42.42.1"], dstIps=["69.69.69.1"], ingressNodeRegex=A, finalNodeRegex=B``` . As for the policy, i tried all three options separately but they all have some thing wrong. The routers' detailed configuration are as follows:
```
hostname R1

interface Loopback0
 ip address 42.42.42.1 255.255.255.0 
!
interface Serial0
 ip address 192.168.42.1 255.255.255.0
!
router bgp 42
 network 42.42.42.0 mask 255.255.255.0
 neighbor 192.168.42.2 remote-as 69
!
```
```
hostname R2

interface Loopback0
 ip address 69.69.69.1 255.255.255.0
!
interface Serial0
 ip address 192.168.42.2 255.255.255.0
!
router bgp 69
 network 69.69.69.0 mask 255.255.255.0
 neighbor 192.168.42.1 remote-as 42
!
```

But when i run ```allinone -cmdfile``` i got some trouble:
```
04/10/23]seed@VM:~/.../batfish-tiramisu$ allinone -cmdfile mycmd
Init'ed and set active network
Uploaded snapshot.
Parsing now.
Status: SUCCESS
PARSING SUMMARY
STATISTICS
  Parsing results:
    Parsed successfully: 2

Summary: 0 (non-assertion) results; 
Start generation
Status: FAILURE
Question: arcRAG actions=[ACCEPTED]
org.batfish.common.BatfishException: Failed to answer question
   at org.batfish.main.Batfish.answer(Batfish.java:635)
   at org.batfish.main.Batfish.run(Batfish.java:3042)
   at org.batfish.main.Driver.lambda$runBatfish$3(Driver.java:580)
   at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
   at org.batfish.mulgraph.Rag.taint_propagate(Rag.java:191)
   at org.batfish.mulgraph.Rag.taint(Rag.java:187)
   at org.batfish.mulgraph.buildRag.run(buildRag.java:124)
   at org.batfish.mulgraph.buildTpg.buildGraph(buildTpg.java:123)
   at org.batfish.mulgraph.buildTpg.run(buildTpg.java:144)
   at org.batfish.symbolic.smt.PropertyChecker.checkRAG(PropertyChecker.java:962)
   at org.batfish.main.Batfish.arcRAG(Batfish.java:3681)
   at org.batfish.question.GraphRAGQuestionPlugin$GraphRAGAnswerer.answer(GraphRAGQuestionPlugin.java:33)
   at org.batfish.main.Batfish.answer(Batfish.java:632)
   ... 3 more

Summary: 0 (non-assertion) results;
```

**I dont konw what was wrong with my input, could your please help me figure this error? I would be very grateful to any of ur help! Thanks a lot.**

**Comment by dhalperi** [comment]
Hi, unfortunately no one who actively contributes to this project is affiliated with Tiramisu, and it looks like the issues are in new code added for that project.

cc: @agember in case this notification gets there.

**Comment by agember** [comment]
@maming-seu I am one of the authors of the Tiramisu project. You can reach me at agemberjacobson@colgate.edu, and we can discuss the issue further.
