### ISSUE TITLE
 unexpected use of keyword interface

### ISSUE THREAD

**Issue by xtz1826277** [batfish/batfish#8727]
I encountered an issue with 'unexpected use of keyword interface' when using Batfish to read the configuration file of FRR.

Here is the configuration file

r2
# This file describes the network interfaces
auto lo
interface lo inet loopback
 address 170.249.69.163/32
 
auto r2-eth0
interface r2-eth0
 
auto r2-eth1
interface r2-eth1
 
auto r2-eth2
interface r2-eth2
 
# ports.conf --
frr version
frr defaults datacenter
!
interface r2-eth0
 ip address 189.158.236.2/24
!
interface r2-eth1
 ip address 158.196.193.130/25
!
interface r2-eth2
 ip address 151.166.2.129/26
route_map map_out_match_ip_prefix_list  permit  1
 set weight 65535
!
route_map map_out_match_interface  permit  1
 set interface r2-eth1
!
!
interface r2-eth0
 ip ospf cost 1
 ip ospf priority 0
!
!
router ospf 100
 ospf router-id 170.249.69.163
 network 151.166.0.0/21 area 0
 network 145.34.96.0/19 area 0
 default-information originate always metric 100 metric-type 2
 default-metric 1
 distance 10
!
!
router bgp 1
 bgp router-id 170.249.69.163
 network 176.0.0.0/4
 network 208.86.99.37/32
 network 170.249.69.162/31
 neighbor 167.112.102.144 remote-as 1
 neighbor 208.86.99.37 remote-as 1
 neighbor 151.166.2.130 remote-as 2
 redistribute connected
 redistribute ospf
 no bgp ebgp-requires-policy
 no bgp network import-check
 neighbor 208.86.99.37 route-reflector-client
 neighbor 151.166.2.130 route-reflector-client
 neighbor 167.112.102.144 disable-link-bw-encoding-ieee
 neighbor 151.166.2.130 disable-link-bw-encoding-ieee
 neighbor 208.86.99.37 maximum-prefix 100
 neighbor upstream capability dynamic
 neighbor peer capability dynamic
 neighbor peer capability dynamic
 neighbor peer capability dynamic
 neighbor cust capability dynamic
!
 address-family ipv4 unicast
  neighbor 167.112.102.144 default-originate
  neighbor 208.86.99.37 default-originate
  neighbor 151.166.2.130 default-originate
  neighbor 167.112.102.144 route_map map_out_match_interface out
  neighbor 208.86.99.37 route_map map_out_match_community_list out
  neighbor 167.112.102.144 route_map map_in_match_as_path_access_list in
  neighbor 208.86.99.37 route_map map_in_match_community_list in
 exit-address-family
!
ip route 197.149.136.224/27 r2-eth2
ip route 197.149.136.224/27 140.254.96.128
route_map map_in_match_as_path_access_list deny 1
route_map map_in_match_interface deny 1
route_map map_in_match_community_list deny 1
route_map map_in_match_ip_prefix_list deny 1
!
end

May I ask how to resolve this error？

**Comment by ratulm** [comment]
Can you share the exact error/stack trace?

**Comment by xtz1826277** [comment]
I use the following code to read the configuration file of FRR
            from pybatfish.client.commands import bf_init_snapshot, bf_session
            from pybatfish.question import bfq
            from pybatfish.question import load_questions
            
            def run(path):
                load_questions()
                bf_init_snapshot(path, overwrite=True)
            
                return bfq.initIssues().answer().frame()
            
            if __name__ == "__main__":
                print(run("/home/xtz/work/Metha-master/results/test5"))


The following error was reported
            java.lang.IllegalStateException: unexpected use of keyword interface
	            at org.batfish.grammar.frr.FrrLexer.INTERFACE_action(FrrLexer.java:329)
	            at org.batfish.grammar.frr.FrrLexer.action(FrrLexer.java:286)
	            at org.antlr.v4.runtime.atn.LexerCustomAction.execute(LexerCustomAction.java:97)
	            at org.antlr.v4.runtime.atn.LexerActionExecutor.execute(LexerActionExecutor.java:168)
	            at org.antlr.v4.runtime.atn.LexerATNSimulator.accept(LexerATNSimulator.java:369)
	            at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(LexerATNSimulator.java:302)
	            at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(LexerATNSimulator.java:233)
	            at org.antlr.v4.runtime.atn.LexerATNSimulator.match(LexerATNSimulator.java:117)
	            at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:141)
	            at org.antlr.v4.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:169)
	            at org.antlr.v4.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:152)
	            at org.antlr.v4.runtime.BufferedTokenStream.nextTokenOnChannel(BufferedTokenStream.java:325)
	            at org.antlr.v4.runtime.CommonTokenStream.adjustSeekIndex(CommonTokenStream.java:70)
	            at org.antlr.v4.runtime.BufferedTokenStream.consume(BufferedTokenStream.java:137)
	            at org.batfish.grammar.BatfishParser.consume(BatfishParser.java:20)
	            at org.antlr.v4.runtime.DefaultErrorStrategy.consumeUntil(DefaultErrorStrategy.java:765)
	            at org.batfish.grammar.BatfishANTLRErrorStrategy.consumeUntilEndOfLine(BatfishANTLRErrorStrategy.java:118)
	            at org.batfish.grammar.BatfishANTLRErrorStrategy.recoverInCurrentNode(BatfishANTLRErrorStrategy.java:227)
	            at org.batfish.grammar.BatfishParser.createErrorNodeLine(BatfishParser.java:57)
	            at org.batfish.grammar.BatfishParserATNSimulator.adaptivePredict(BatfishParserATNSimulator.java:70)
	            at org.batfish.grammar.frr.FrrParser.s_interface(FrrParser.java:8812)
	            at org.batfish.grammar.frr.FrrParser.statement(FrrParser.java:505)
	            at org.batfish.grammar.frr.FrrParser.frr_configuration(FrrParser.java:372)
	            at org.batfish.grammar.frr.FrrCombinedParser.parse(FrrCombinedParser.java:29)
	            at org.batfish.grammar.cumulus_concatenated.CumulusConcatenatedControlPlaneExtractor.parseFrrFile(CumulusConcatenatedControlPlaneExtractor.java:101)
	            at org.batfish.grammar.cumulus_concatenated.CumulusConcatenatedControlPlaneExtractor.processParseTree(CumulusConcatenatedControlPlaneExtractor.java:95)
	            at org.batfish.job.ParseVendorConfigurationJob.parseFile(ParseVendorConfigurationJob.java:668)
	            at org.batfish.job.ParseVendorConfigurationJob.parseFiles(ParseVendorConfigurationJob.java:342)
	            at org.batfish.job.ParseVendorConfigurationJob.parse(ParseVendorConfigurationJob.java:721)
	            at org.batfish.main.Batfish.getOrParse(Batfish.java:2495)
	            at org.batfish.main.Batfish.lambda$serializeNetworkConfigs$49(Batfish.java:2579)
	            at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	            at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	            at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	            at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	            at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
	            at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
	            at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	            at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	            at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	            at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	            at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	            at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	            at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


Here is the configuration file I used
r0
# This file describes the network interfaces
auto lo
interface lo inet loopback
 address 167.112.102.144/32
 
auto r0-eth0
interface r0-eth0
 
auto r0-eth1
interface r0-eth1
 
# ports.conf --
frr version
frr defaults datacenter
!
interface r0-eth0
 ip address 182.222.108.1/25
!
interface r0-eth1
 ip address 189.158.236.1/24
route_map map_out_match_ip_prefix_list deny 1
 set weight 1000
 match ip address prefix-list prefix_list_0
!

interface r0-eth1
 ip ospf cost 1
 ip ospf priority 10
 ip ospf network point-to-point
!
interface r0-eth0
 ip ospf cost 1
 ip ospf priority 10
 ip ospf network point-to-point
!
!
router ospf 100
 ospf router-id 167.112.102.144
 network 189.158.236.0/24 area 1
 network 208.86.99.37/32 area 1
 network 182.222.108.0/30 area 1
 network 151.166.0.0/21 area 0
 network 145.34.96.0/19 area 0
 area 0 range 167.112.102.144/32
 default-information originatemetric 100 metric-type 2
 default-metric 100
 distance 100
 redistribute static
 redistribute bgp
!
!
router bgp 1
 bgp router-id 167.112.102.144
 network 176.0.0.0/4
 network 208.86.99.37/32
 network 170.249.69.162/31
 neighbor 208.86.99.37 remote-as 1
 neighbor 170.249.69.163 remote-as 1
 redistribute connected
 aggregate-address 167.112.102.144/32 matching-MED-only
 no bgp ebgp-requires-policy
 neighbor 208.86.99.37 disable-link-bw-encoding-ieee
 neighbor 170.249.69.163 disable-link-bw-encoding-ieee
 neighbor upstream capability dynamic
 neighbor upstream capability dynamic
 neighbor cust capability dynamic
 neighbor cust capability dynamic
!
 address-family ipv4 unicast
  neighbor 170.249.69.163 default-originate
  neighbor 208.86.99.37 route_map map_out_match_as_path_access_list out
  neighbor 170.249.69.163 route_map map_out_match_ip_prefix_list out
  neighbor 208.86.99.37 route_map map_in_match_interface in
  neighbor 170.249.69.163 route_map map_in_match_ip_prefix_list in
 exit-address-family
!
ip route 210.101.174.40/29 r0-eth0
ip route 210.101.174.40/29 210.101.174.40
route_map map_in_match_as_path_access_list deny 1
route_map map_in_match_community_list deny 1
route_map map_in_match_ip_prefix_list deny 1
route_map map_out_match_interface deny 1
route_map map_out_match_community_list deny 1
!
end

**Comment by ratulm** [comment]
@xtz1826277 - thanks for sharing that. we'll TAL.

@arifogel - does anything obvious jump out to you here?

**Comment by ratulm** [comment]
@xtz1826277 - I am unable to repro your issue with the file you provided. I get 31 init issues, some of which are attached. 

Are you running into the problem with unmodified Batfish or with locally modified parser/lexer? The error you are seeing is in auto-generated code by Antlr based on the grammar files. 

<img width="1082" alt="Screen Shot 2023-06-19 at 5 06 41 PM" src="https://github.com/batfish/batfish/assets/4723124/3f07f6d3-182b-460d-9eb9-18cd6a5a3e7e">

**Comment by xtz1826277** [comment]
I found the error, in the route-map I used set interface.
I would like to ask how many FRR configurations are supported by Batfish (all, most, or some) and is there any documentation on how to use them?

**Comment by ratulm** [comment]
When a configuration is not supported, a warning will show up in initIssues.  You can also get a line-by-line analysis of a config file via the annotate tool: https://batfish.readthedocs.io/en/latest/config_annotation.html

I am closing this issue for now. Feel free to re-open if something is still pending.
