### ISSUE TITLE
Add support for nve interfaces for Cisco

### ISSUE THREAD

**Issue by saparikh** [batfish/batfish#910]
Cisco NX-OS devices creates NVE interfaces for VXLAN EVPN deployments.

https://www.cisco.com/c/en/us/support/docs/switches/nexus-9000-series-switches/118978-config-vxlan-00.html

Batfish does not recognize NVE interfaces, which causes parsing to fail.

**Comment by dhalperi** [comment]
Can you post a sample configuration snippet as well as the actual stack trace?

**Comment by saparikh** [comment]
error message:
```
       org.batfish.common.BatfishException: Error post-processing parse tree of configuration file: '/Users/samir/git/batfish/containers/chealth/testrigs/tr_ebc7c83f-1d25-4249-be71-6b81e7a1ec9f/testrig/configs/NDUO1L3-LFN-A-AA41.cfg'
        at org.batfish.job.ParseVendorConfigurationJob.call(ParseVendorConfigurationJob.java:330)
        at org.batfish.job.ParseVendorConfigurationJob.call(ParseVendorConfigurationJob.java:32)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.batfish.common.BatfishException: Error fetching interface name at: 205:0: interface nve1
  no shutdown

        at org.batfish.grammar.cisco.CiscoControlPlaneExtractor.enterS_interface(CiscoControlPlaneExtractor.java:1897)
        at org.batfish.grammar.cisco.CiscoParser$S_interfaceContext.enterRule(CiscoParser.java)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:42)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.batfish.grammar.cisco.CiscoControlPlaneExtractor.processParseTree(CiscoControlPlaneExtractor.java:6322)
        at org.batfish.job.ParseVendorConfigurationJob.call(ParseVendorConfigurationJob.java:306)
        ... 7 more
Caused by: org.batfish.common.BatfishException: Invalid interface name prefix: 'nve'
        at org.batfish.representation.cisco.CiscoConfiguration.getCanonicalInterfaceNamePrefix(CiscoConfiguration.java:228)
        at org.batfish.grammar.cisco.CiscoControlPlaneExtractor.enterS_interface(CiscoControlPlaneExtractor.java:1894)
        ... 14 more
Processing: '/Users/samir/git/batfish/containers/chealth/testrigs/tr_ebc7c83f-1d25-4249-be71-6b81e7a1ec9f/testrig/configs/NDUO1L3-LFN-A-AA41.cfg'
```

configuration snippet for the interface
```
interface nve1
  no shutdown
  source-interface loopback0
  host-reachability protocol bgp 
  member vni 5029
    mcast-group 225.5.0.126
  member vni 5100
    mcast-group 225.5.0.126
  member vni 35000 associate-vrf
```
