### ISSUE TITLE
Error handling if interface_blacklist file is not accurate

### ISSUE THREAD

**Issue by saparikh** [batfish/batfish#914]
If there is an incorrect node-name in the interface_blacklist file and you run a query to find all of the neighbor, Batfish returns an exception.

It would best if when the interface_blacklist file is processed that a warning is generated for any incorrect node-names or interface-names and then they are stripped from the blacklist.

```
In [28]: bfq.neighbors().answer()
status: TRYINGTOASSIGN
.... no task information
status: TERMINATEDABNORMALLY
.... Wed Feb  7 15:37:05 2018 PST Begin job
{
  "status": "FAILURE", 
  "summary": {
    "numResults": 0, 
    "numPassed": 0, 
    "numFailed": 0
  }, 
  "answerElements": [
    {
      "answer": [
        "org.batfish.common.BatfishException: Batfish job failed", 
        "   at org.batfish.main.Driver$2.run(Driver.java:592)", 
        "Caused by: org.batfish.common.BatfishException: Cannot continue: environment 'env_default' is invalid:", 
        "Results of environment processing and validation:", 
        "ENVIRONMENT IS INVALID!", 
        "undefinedInterfaceBlacklistNodes:", 
        "  name1", 
        "  name2", 
        "", 
        "   at org.batfish.main.Batfish.loadConfigurations(Batfish.java:2337)", 
        "   at org.batfish.main.Batfish.answer(Batfish.java:589)", 
        "   at org.batfish.main.Batfish.run(Batfish.java:3726)", 
        "   at org.batfish.main.Driver$2.run(Driver.java:564)"
      ], 
      "class": "org.batfish.common.BatfishException$BatfishStackTrace"
    }
  ]
}
```

**Comment by sfraint** [comment]
Looks like this is no longer an issue.
Invalid blacklist elements persist in the saved blacklist but are ignored when generating topology.
