### ISSUE TITLE
Parsing cisco_style_acl1 in unit-tests test rig fails

### ISSUE THREAD

**Issue by agember** [batfish/batfish#938]
```
Exception in thread "main" java.lang.NullPointerException
        at java.util.TreeMap.getEntry(TreeMap.java:347)
        at java.util.TreeMap.get(TreeMap.java:278)
        at java.util.Map.computeIfAbsent(Map.java:955)
        at org.batfish.vendor.VendorConfiguration.unused(VendorConfiguration.java:134)
        at org.batfish.representation.cisco.CiscoConfiguration.warnUnusedStructure(CiscoConfiguration.java:4100)
        at org.batfish.representation.cisco.CiscoConfiguration.warnUnusedIpAccessLists(CiscoConfiguration.java:4054)
        at org.batfish.representation.cisco.CiscoConfiguration.toVendorIndependentConfiguration(CiscoConfiguration.java:3851)```

**Comment by dhalperi** [comment]
Hi @agember ,

I'd like to take a look at this issue but I'm having trouble reproducing. What did you do to get this stack trace?

From what I can tell, the file is itself parsed during normal test operation https://github.com/batfish/batfish/blob/master/tests/basic/commands#L76-L78, and we also `get nodes` so that all the files were parsed.

Is there something additional that I can do to trigger this behavior?

**Comment by agember** [comment]
I am directly invoking the BatfishCombinedParser on the cisco_style_acl1 file from another Java program that links in the Batfish code. It is possible I'm not setting something up correctly in my direct invocation of the parser, which is causing the bug. You can disregard this if you cannot reproduce it using the normal testing process.
